//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reflection.EF.Production
{
    using System;
    using System.Collections.Generic;

    public partial class ESO_T001 : ObjectBase
    {
        public int id { get; set; }
        public string doc_no { get; set; }
        public string doc_cat { get; set; }
        public string doc_type { get; set; }
        public Nullable<System.DateTime> entry_dt { get; set; }
        public Nullable<System.DateTime> prod_dt { get; set; }
        public string unit_code { get; set; }
        public string machinecode { get; set; }
        public string defects { get; set; }
        public Nullable<decimal> rej_qty_1 { get; set; }
        public Nullable<decimal> rej_qty_2 { get; set; }
        public Nullable<decimal> tot_rej { get; set; }
        public string sort_by { get; set; }
        public string note { get; set; }
        public string shift { get; set; }
        public Nullable<bool> active { get; set; }
        public string add_by { get; set; }
        public System.DateTime add_date { get; set; }
        public string editby { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string comp_code { get; set; }
        public string location_Id { get; set; }
        public Nullable<decimal> rej_qty_3 { get; set; }
        public string ItemCode { get; set; }
        public string batch_no { get; set; }
        public string order_no { get; set; }
        public string ref_doc_no { get; set; }
        public string EmpId { get; set; }
        public string shift_incharge { get; set; }      
        public Nullable<decimal> excess_qty { get; set; }
        public Nullable<decimal> counter_qty { get; set; }
        public Nullable<decimal> uc_qty { get; set; }
        public string sort_cat { get; set; }
        public string sort_type { get; set; }
        public Nullable<decimal> sorted_qty { get; set; }
        public string t_status { get; set; }
        public string status_remark { get; set; }
        public Nullable<decimal> refill_qty { get; set; }
        public string plant { get; set; }
        public string OperatorName { get; set; }
        public string ShiftInchargeName { get; set; }
        public Nullable<bool> ButtonAIsChecked { get; set; }
        public Nullable<bool> ButtonBIsChecked { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string rpttpe { get; set; }  
        public string barcode { get; set; }
        public string ItemName { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public decimal? sample_qty { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public Nullable<System.DateTime> out_date { get; set; }
        public decimal? c_qty { get; set; }

        //scalar fields
        public System.DateTime? Fromdt { get; set; }
        public System.DateTime? Todt { get; set; }
        public string EmpId1 { get; set; }
        public string qc_person1 { get; set; }
        public string sshift { get; set; }
        public string item { get; set; }
        public string machine { get; set; }
        public string con_no { get; set; }
        public string t_display { get; set; }
        public string grade { get; set; }
        public string wc_code { get; set; }
        public string counter_remark { get; set; }

        

    }



}
