using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Reflection.EF.Procurement
{


    public partial class PUR_T002_A : ObjectBase
    {
        public string po_no { get; set; }
        public System.DateTime po_date { get; set; }
        public Nullable<int> id { get; set; }
        public string doc_type { get; set; }
        public string doc_cat { get; set; }
        public string quotation_no { get; set; }
        public Nullable<System.DateTime> quotation_date { get; set; }
        public Nullable<System.DateTime> quotation_validity { get; set; }
        public Nullable<bool> sample { get; set; }
        public string ref_doc_no { get; set; }
        public Nullable<System.DateTime> ref_doc_date { get; set; }
        public Nullable<System.DateTime> valid_from_date { get; set; }
        public Nullable<System.DateTime> valid_to_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string buyer { get; set; }
        public string supplier_EmpId { get; set; }
        public string supplier_EmpName { get; set; }
        public string po_code { get; set; }
        public string pg_code { get; set; }
        public string cost_center { get; set; }
        public string j_code { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string PartyId { get; set; }
        public string party_name { get; set; }
        public string referring_party { get; set; }
        public string del_address_id { get; set; }
        public string bill_address_id { get; set; }
        public string address { get; set; }
        public string address1 { get; set; }
        public string country_nm { get; set; }
        public string state_nm { get; set; }
        public string city { get; set; }
        public string pincode { get; set; }
        public string phone_no { get; set; }
        public string mobile_no { get; set; }
        public string phone_ext { get; set; }
        public string mail_id { get; set; }
        public string web_site { get; set; }
        public string fp_code { get; set; }
        public Nullable<decimal> amount_untaxed { get; set; }
        public string stock_location_id { get; set; }
        public Nullable<decimal> amount_tax { get; set; }
        public Nullable<int> pricelist_id { get; set; }
        public string cat_no { get; set; }
        public string wa_code { get; set; }
        public string p_term_code { get; set; }
        public string curr_code { get; set; }
        public Nullable<decimal> ex_rate { get; set; }
        public string supplying_plant { get; set; }
        public string incoterms { get; set; }
        public string supplier_ref { get; set; }
        public Nullable<System.DateTime> supplier_ref_date { get; set; }
        public Nullable<System.DateTime> date_approve { get; set; }
        public Nullable<decimal> amount_total { get; set; }
        public string amt_in_words { get; set; }
        public string down_ind { get; set; }
        public Nullable<decimal> down_per { get; set; }
        public Nullable<decimal> down_pay { get; set; }
        public Nullable<System.DateTime> down_date { get; set; }
        public string reference { get; set; }
        public string notes { get; set; }
        public string invoice_method { get; set; }
        public Nullable<bool> shipped { get; set; }
        public Nullable<System.DateTime> shipped_date { get; set; }
        public string validator_code { get; set; }
        public Nullable<System.DateTime> min_planned_date { get; set; }
        public string rel_sts { get; set; }
        public string t_status { get; set; }
        public string transacion_type { get; set; }
        public string status_quotation { get; set; }
        public string location_Id { get; set; }
        public string comp_code { get; set; }
        public string version { get; set; }
        public Nullable<bool> active { get; set; }
        public string add_by { get; set; }
        public System.DateTime add_date { get; set; }
        public string editby { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string local_export_ind { get; set; }
        public Nullable<System.DateTime> app_closing_dt { get; set; }
        public Nullable<System.DateTime> quotation_deadline { get; set; }
        public string bid_inv_no { get; set; }
        public Nullable<System.DateTime> quotation_submt_dt { get; set; }
        public Nullable<decimal> shrot_excess_amt { get; set; }
        public string shrot_excess_flag { get; set; }
        public string delivery_ind { get; set; }
        public string gr_ind { get; set; }
        public string invoice_ind { get; set; }
        public string gr_inv_ind { get; set; }
        public string order_ack_ind { get; set; }
        public string order_ack_no { get; set; }
        public Nullable<System.DateTime> order_ack_date { get; set; }
        public Nullable<bool> acknowledged { get; set; }
        public string pur_agree_no { get; set; }
        public string pur_agree_item_cd { get; set; }
        public string ref_doc_type { get; set; }
        public string cust_mat_no { get; set; }
        public Nullable<decimal> abs_deviation_qty { get; set; }
        public Nullable<decimal> per_deviation_qty { get; set; }
        public Nullable<decimal> over_del_tol { get; set; }
        public Nullable<decimal> under_del_tol { get; set; }
        public string bank_code { get; set; }
        public string revision_no { get; set; }
        public string revision_ind { get; set; }
        public string rev_ref_no { get; set; }
        public string cf_agent_cd { get; set; }
        public Nullable<decimal> qty_tol { get; set; }
        public Nullable<decimal> amt_tol { get; set; }
        public string nastro_bank_cd { get; set; }
        public string account_no { get; set; }
        public string swift_code { get; set; }
        public string ifsc_code { get; set; }
        public string terms_cond { get; set; }
        public Nullable<bool> abg_flag { get; set; }
        public Nullable<int> abg_days { get; set; }
        public Nullable<System.DateTime> abg_release_date { get; set; }
        public string release_mode { get; set; }
        public string transporter { get; set; }
        public string gl_code { get; set; }
        public Nullable<decimal> round_up { get; set; }
        public Nullable<decimal> roundup_total { get; set; }
        public string sto_ind { get; set; }
        public string rec_plant { get; set; }
        public string doc_type_user { get; set; }
        public string doc_desc { get; set; }
        public string BuyerName { get; set; }
        public string pur_org { get; set; }
        public string pg_name { get; set; }
        public string cost_center_Desc { get; set; }
        public string inco_desc { get; set; }
        public string wa_name { get; set; }
        public string validator_name { get; set; }
        public string PaymentTerms { get; set; }
        public string dcat_name { get; set; }
        public string supplyingplant_name { get; set; }
        public string rec_plant_name { get; set; }
        public string status_remark { get; set; }
        public string EmailId { get; set; }
        public string PersnEmailId { get; set; }
        public string doc_history_no { get; set; }
        public Nullable<System.DateTime> CSTDate { get; set; }
        public Nullable<System.DateTime> VATDate { get; set; }
        public string CSTNo { get; set; }
        public string VATNo { get; set; }
        public string PanNo { get; set; }
        public string EccCode { get; set; }
        public string TNo { get; set; }
        public Nullable<decimal> order_limit { get; set; }
        public Nullable<bool> order_limit_tax { get; set; }
        public string symbol { get; set; }
        public string incoterm2 { get; set; }
        public Nullable<System.DateTime> ref_date { get; set; }
        public string fin_year { get; set; }
        public string posting_period { get; set; }
        public string store_code { get; set; }
        public string para1 { get; set; }
        public string para2 { get; set; }
        public string para3 { get; set; }
        public string pre_carrage { get; set; }
        public string pre_carrage_place { get; set; }
        public string country_code { get; set; }
        public string port_load { get; set; }
        public string port_desc { get; set; }
        public string port_final { get; set; }
        public string final_dest { get; set; }
        public string ship_terms { get; set; }
        public string lic_cod { get; set; }
        public string adv_lic_cd { get; set; }
        public string org_country_cd { get; set; }
        public string pack_rem { get; set; }
        public string ship_mark { get; set; }
        public string tr_mode { get; set; }
        public string tr_type { get; set; }
        public string local_export { get; set; }
        public string ind_trade { get; set; }
        public Nullable<decimal> gross_wt { get; set; }
        public Nullable<decimal> net_wt { get; set; }
        public string unit_code { get; set; }
        public string volume_unit { get; set; }
        public string ref_version { get; set; }
        public Nullable<decimal> volume { get; set; }
        public string vendor_bank_code { get; set; }
        public string notify_party { get; set; }
        public string shipping_mark { get; set; }
        public string insurance { get; set; }
        public string packing { get; set; }
        public string transhipment { get; set; }
        public string partshipment { get; set; }
        public Nullable<System.DateTime> shipment_date { get; set; }
        public Nullable<System.DateTime> validity_date { get; set; }
        public string payment_mode { get; set; }
        public Nullable<bool> qty_percent { get; set; }
        public Nullable<bool> amt_percent { get; set; }
        public Nullable<int> ref_party_contact { get; set; }
        public string ref_contact_name { get; set; }
        public string language { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public string remark4 { get; set; }
        public string location { get; set; }
        public string title { get; set; }
        public Nullable<decimal> net_value { get; set; }
        public string withholding_tax { get; set; }
        public Nullable<decimal> withholding_value { get; set; }
        public string note { get; set; }
        public string lang_key { get; set; }
        public string remark { get; set; }
        public string incoterms1 { get; set; }
        public string incoterms2 { get; set; }
        public string principal_no { get; set; }
        public string purchase_ind { get; set; }
        public Nullable<decimal> local_amount_tax { get; set; }
        public Nullable<decimal> local_amount_total { get; set; }
        public Nullable<decimal> local_round_up { get; set; }
        public Nullable<decimal> local_roundup_total { get; set; }
        public Nullable<decimal> local_net_value { get; set; }
        public Nullable<decimal> other_charges { get; set; }
        public Nullable<decimal> withholding_ex_amt { get; set; }
        public string bom_no { get; set; }
        public Nullable<decimal> gross_value { get; set; }
        public Nullable<decimal> effective_value { get; set; }
        public Nullable<decimal> disc_amt { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public string EmpEmailId { get; set; }
        public string EmpMobNo { get; set; }
        public string PhNo { get; set; }
        public string FaxNo { get; set; }
        public string FormDescription { get; set; }
        public Nullable<int> form_type { get; set; }
        public string refer_by { get; set; }
        //Added by Priya
        public string gst_PartyId { get; set; }
        public string buss_place { get; set; }
        public string plc_name { get; set; }
        //GST by Priya
        public string STP_gstinno { get; set; }
        public string DTP_gstinno { get; set; }
        public Nullable<System.DateTime> STP_gstindate { get; set; }
        public Nullable<System.DateTime> DTP_gstindate { get; set; }
        public string STP_state_code { get; set; }
        public string DTP_state_code { get; set; }
        public string data1 { get; set; }
        public string owner_name { get; set; }
        public string DEmp_PhNo { get; set; }
        public string DEmp_FaxNo { get; set; }
        public string DEmp_EmailId { get; set; }
        public string t_display { get; set; }
        public string _ts_code { get; set; }
        public string PersnFName { get; set; }
        public string PersnLName { get; set; }
        public string PersnMobNo { get; set; }
        public string shipping_address { get; set; }
        public string add_code { get; set; }
        public string add_code_del { get; set; }
        public string add_code_bil { get; set; }

        public string delivery_address { get; set; }
        public string billing_address { get; set; }
        public string delivery_state_code { get; set; }
        public string billing_state_code { get; set; }
        public string delivery_GSTIN { get; set; }
        public string billing_GSTIN { get; set; }
        public string doc_format { get; set; }
        public string tr_name { get; set; }
        public string letter_text { get; set; }
        public string body_text { get; set; }
        public string header_text { get; set; }
        public string footer_text { get; set; }

        public string emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_mail { get; set; }
        public string emp_contact { get; set; }
        public string supplier_address { get; set; }
        public string instructions { get; set; }
        public byte[] sig { get; set; }
    }
    public partial class PUR_T002_B
    {
        public int id { get; set; }
        public string po_no { get; set; }
        public int line_id { get; set; }
        public string ItemCode { get; set; }
        public string req_no { get; set; }
        public Nullable<int> planning_line_id { get; set; }
        public string item_cat { get; set; }
        public string description { get; set; }
        public string sku { get; set; }
        public string sku_desc { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string unit_code { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public string tax_id { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public string move_dest_id { get; set; }
        public string PartyId { get; set; }
        public Nullable<bool> invoiced { get; set; }
        public Nullable<System.DateTime> date_planned { get; set; }
        public string acc_code { get; set; }
        public string batch_no { get; set; }
        public Nullable<bool> batch_split_allow { get; set; }
        public Nullable<decimal> conversn_fact { get; set; }
        public Nullable<decimal> gross_wt { get; set; }
        public Nullable<decimal> net_wt { get; set; }
        public string weight_unit { get; set; }
        public Nullable<decimal> volume { get; set; }
        public string vol_unit { get; set; }
        public string store_code { get; set; }
        public string gr_ind { get; set; }
        public string inv_ind { get; set; }
        public string rfq_no { get; set; }
        public Nullable<int> rfq_item_no { get; set; }
        public string pur_req_no { get; set; }
        public Nullable<int> pur_req_item { get; set; }
        public Nullable<int> pur_req_item_row_id { get; set; }
        public string issue_store_code { get; set; }
        public string t_status { get; set; }
        public string comp_code { get; set; }
        public string location_Id { get; set; }
        public Nullable<bool> active { get; set; }
        public string user_source1 { get; set; }
        public string user_source2 { get; set; }
        public string add_by { get; set; }
        public System.DateTime add_date { get; set; }
        public string editby { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string bid_inv_no { get; set; }
        public string quotation_no { get; set; }
        public Nullable<decimal> shrot_excess_amt { get; set; }
        public string shrot_excess_flag { get; set; }
        public string delivery_ind { get; set; }
        public string gr_inv_ind { get; set; }
        public string order_ack_ind { get; set; }
        public string order_ack_no { get; set; }
        public Nullable<System.DateTime> order_ack_date { get; set; }
        public Nullable<bool> acknowledged { get; set; }
        public string pur_agree_no { get; set; }
        public Nullable<int> pur_agree_item_cd { get; set; }
        public string ref_doc_no { get; set; }
        public Nullable<System.DateTime> ref_doc_date { get; set; }
        public string ref_doc_type { get; set; }
        public string cust_mat_no { get; set; }
        public Nullable<decimal> abs_deviation_qty { get; set; }
        public Nullable<decimal> per_deviation_qty { get; set; }
        public Nullable<decimal> over_del_tol { get; set; }
        public Nullable<decimal> under_del_tol { get; set; }
        public string batch_split { get; set; }
        public string p_term_code { get; set; }
        public string terms_cond { get; set; }
        public string serviceNo { get; set; }
        public string gl_code { get; set; }
        public string incoterms { get; set; }
        public string rec_plant { get; set; }
        public string supplying_plant { get; set; }
        public string status_remark { get; set; }
        public string remark { get; set; }
        public string textdata { get; set; }
        public int ref_item_line_id { get; set; }
        public string account_analytic_id { get; set; }
        public string wa_code { get; set; }
        public string para1 { get; set; }
        public string para2 { get; set; }
        public string para3 { get; set; }
        public Nullable<int> para4 { get; set; }
        public string para5 { get; set; }
        public string para6 { get; set; }
        public string para7 { get; set; }
        public Nullable<decimal> para8 { get; set; }
        public string para9 { get; set; }
        public string para10 { get; set; }
        public string para11 { get; set; }
        public Nullable<bool> para12 { get; set; }
        public Nullable<System.DateTime> para13 { get; set; }
        public string para14 { get; set; }
        public string para15 { get; set; }
        public string para16 { get; set; }
        public Nullable<decimal> para17 { get; set; }
        public string para18 { get; set; }
        public string para19 { get; set; }
        public string para20 { get; set; }
        public string para21 { get; set; }
        public string para22 { get; set; }
        public string para23 { get; set; }
        public Nullable<int> para24 { get; set; }
        public string para25 { get; set; }
        public string para26 { get; set; }
        public string para27 { get; set; }
        public Nullable<int> para28 { get; set; }
        public string cust_ref { get; set; }
        public Nullable<System.DateTime> cust_ref_date { get; set; }
        public Nullable<int> pack_style { get; set; }
        public string fin_year { get; set; }
        public string posting_period { get; set; }
        public string rel_delivery { get; set; }
        public string rel_billing { get; set; }
        public Nullable<int> item_no_ref_item { get; set; }
        public string net_value { get; set; }
        public Nullable<int> source_doc_item_id { get; set; }
        public Nullable<int> order_doc_item_id { get; set; }
        public Nullable<int> ref_sales_item_id { get; set; }
        public string ref_order_no { get; set; }
        public Nullable<int> sales_item_line_id { get; set; }
        public string sono { get; set; }
        public string recipient_location { get; set; }
        public string requester_name { get; set; }
        public Nullable<int> per_req_item_id { get; set; }
        public string pkgs_no { get; set; }
        public string incoterms1 { get; set; }
        public string incoterms2 { get; set; }
        public string shipping_inst { get; set; }
        public string inter_article_no { get; set; }
        public string base_unit { get; set; }
        public string valuation_cat { get; set; }
        public string valuation_type { get; set; }
        public Nullable<decimal> underdelivery_limit { get; set; }
        public string overdelivery_ind { get; set; }
        public Nullable<decimal> overdelivery_limit { get; set; }
        public Nullable<int> day_reminder1 { get; set; }
        public Nullable<int> day_reminder2 { get; set; }
        public Nullable<int> day_reminder3 { get; set; }
        public Nullable<decimal> cumulative_qty { get; set; }
        public Nullable<System.DateTime> reconciliation_date { get; set; }
        public Nullable<decimal> cash_disc_per1 { get; set; }
        public Nullable<decimal> cash_disc_per2 { get; set; }
        public Nullable<decimal> cash_disc_per3 { get; set; }
        public Nullable<int> cash_disc_days1 { get; set; }
        public Nullable<int> cash_disc_days2 { get; set; }
        public Nullable<int> cash_disc_days3 { get; set; }
        public string principal_no { get; set; }
        public string principal_item_no { get; set; }
        public Nullable<decimal> local_discount { get; set; }
        public Nullable<decimal> local_sub_total { get; set; }
        public Nullable<decimal> local_net_value { get; set; }
        public string bom_no { get; set; }
        public string symbol { get; set; }
        public Nullable<decimal> gross_value { get; set; }
        public Nullable<decimal> effective_value { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public string discount_type { get; set; }
        public Nullable<decimal> discount_amt { get; set; }
        public string article_no { get; set; }
        public Nullable<int> ref_item_row_id { get; set; }
        public Nullable<int> planning_row_id { get; set; }
        public Nullable<int> per_req_item_row_id { get; set; }
        public Nullable<int> pur_agree_item_row_id { get; set; }
        public Nullable<int> source_doc_item_row_id { get; set; }
        public Nullable<int> order_doc_item_row_id { get; set; }
        public string Mat_Condition { get; set; }
        public string Type { get; set; }
        public string Make { get; set; }
        //Added by Priya
        public string planning_no { get; set; }
        public string notify_party { get; set; }
        public Nullable<int> service_id { get; set; }
        public string rfq_status { get; set; }
        public Nullable<decimal> num_order_unit { get; set; }
        public Nullable<decimal> denum_order_unit { get; set; }
        public Nullable<decimal> num_order_base_unit { get; set; }
        public Nullable<decimal> denum_order_base_unit { get; set; }
        public string ild_ul_del { get; set; }
        public string ind_rej { get; set; }
        public string ind_del_completed { get; set; }
        public string ind_invoice_final { get; set; }
        public string assign_no { get; set; }
        public string ind_gr_inv_verify { get; set; }
        public string budget_code { get; set; }
        public string cost_center { get; set; }
        public string profit_center { get; set; }
        public string time_zone { get; set; }
        public string tracking_no { get; set; }
        //Added by Priya
        public Nullable<decimal> bal_qty { get; set; }
        public string bill_address_id { get; set; }
        public string del_address_id { get; set; }
        public string buss_place { get; set; }
        public string hs_code { get; set; }
        public string hsn_code { get; set; }
        public string hsn_code2 { get; set; }
        //GST
        public string hs_code2 { get; set; }
        public string t_display { get; set; }

    }
    public partial class PUR_T002_C
    {
        public int id { get; set; }
        public int line_id { get; set; }
        public int ref_item_line_id { get; set; }
        public string po_no { get; set; }
        public int? po_item_row_id { get; set; }
        public int? sch_row_id { get; set; }
        public bool? active { get; set; }
        public string t_status { get; set; }
        public string client { get; set; }
        public string comp_code { get; set; }
        public string location_id { get; set; }
        public string item_code { get; set; }
        public string sku { get; set; }
        public string store_code { get; set; }
        public string batch_no { get; set; }
        public decimal qty { get; set; }
        public string unit_code { get; set; }
        public string reserv_no { get; set; }
        public int? reserv_item_row_id { get; set; }
        public string record_type { get; set; }
        public string requirement_type { get; set; }
        public string bom_no { get; set; }
        public int? bom_item_row_id { get; set; }
        public string routing_no { get; set; }
        public int? op_seq { get; set; }
        public string operation_no { get; set; }
        public int? plan_counter { get; set; }
        public string object_no { get; set; }
        public decimal? op_scrap { get; set; }
        public decimal? comp_scrap { get; set; }
        public string order_no { get; set; }
        public int? order_item_row_id { get; set; }


        //Scalar Fields
        public string item_name { get; set; }
        public string sku_desc { get; set; }
        public string t_display { get; set; }
    }
    public partial class PUR_T002_D
    {
        public int id { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<int> sequence { get; set; }
        public string doc_no { get; set; }
        public string req_no { get; set; }
        public string manual { get; set; }
        public Nullable<decimal> base_amount { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> @base { get; set; }
        public Nullable<int> tax_code_id { get; set; }
        public Nullable<int> account_analytic_id { get; set; }
        public Nullable<int> base_code_id { get; set; }
        public string tax_name { get; set; }
        public string gl_code { get; set; }
        public string ItemCode { get; set; }
        public string sku { get; set; }
        public Nullable<int> item_line_id { get; set; }
        public Nullable<int> fin_year { get; set; }
        public Nullable<bool> active { get; set; }
        public string location_Id { get; set; }
        public string comp_code { get; set; }
        public string dc_ind { get; set; }
        public string curr_code { get; set; }
        public Nullable<decimal> exch_rate { get; set; }
        public string local_curr { get; set; }
        public Nullable<decimal> amt_local_curr { get; set; }
        public string fix_per { get; set; }
        public string symbol { get; set; }
        public string t_display { get; set; }

    }
    public partial class PUR_T002_E
    {
        public int id { get; set; }
        public Nullable<int> po_line_id { get; set; }
        public string po_no { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public string doc_no { get; set; }
    }
    public partial class PUR_T002_F
    {
        public int ID { get; set; }
        public string product_uom { get; set; }
        public Nullable<int> sequence { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public Nullable<decimal> duration { get; set; }
        public Nullable<System.DateTime> constraint_date_end { get; set; }
        public Nullable<System.DateTime> constraint_date_start { get; set; }
        public string name { get; set; }
        public string project_id { get; set; }
        public string t_status { get; set; }
        public string add_by { get; set; }
        public Nullable<System.DateTime> add_date { get; set; }
        public string editby { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
    }
    public partial class PUR_T002_G
    {
        public int id { get; set; }
        public string po_no { get; set; }
        public Nullable<System.DateTime> approve_dt { get; set; }
        public Nullable<bool> approve_status { get; set; }
        public string user_source1 { get; set; }
        public string user_source2 { get; set; }
        public string add_by { get; set; }
        public System.DateTime add_date { get; set; }
        public string editby { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
    }
    public partial class PUR_T002_H
    {
        public string tc_code { get; set; }
        public int id { get; set; }
        public Nullable<int> sequence_code { get; set; }
        public string doc_no { get; set; }
        public string doc_cat { get; set; }
        public string doc_type { get; set; }
        public Nullable<System.DateTime> doc_date { get; set; }
        public string comp_code { get; set; }
        public string location_Id { get; set; }
        public string client { get; set; }
        public string PartyId { get; set; }
        public string sg_code { get; set; }
        public string so_code { get; set; }
        public string CatCode { get; set; }
        public string ItemTypeCd { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> sequence1 { get; set; }
        public Nullable<int> sequence2 { get; set; }
        public Nullable<int> sequence3 { get; set; }
        public string short_text { get; set; }
        public string long_text { get; set; }
        public string unit_code { get; set; }
        public Nullable<bool> compulsory { get; set; }
        public string language_code { get; set; }
        public string con_type { get; set; }
        public string con_desc { get; set; }
        public string info_group { get; set; }
        public string info_desc { get; set; }
        public string info_sub_group { get; set; }
        public string info_sub_desc { get; set; }
        public Nullable<bool> active { get; set; }
        public string user_source1 { get; set; }
        public string user_source2 { get; set; }
        public string add_by { get; set; }
        public System.DateTime add_date { get; set; }
        public string editby { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }



    }
    public partial class PUR_T004_A
    {
        public int id { get; set; }
        public string sch_no { get; set; }
        public Nullable<System.DateTime> sch_date { get; set; }
        public string sch_mode { get; set; }
        public string PartyId { get; set; }
        public string t_status { get; set; }
        public string location_Id { get; set; }
        public Nullable<bool> active { get; set; }
        public string user_source1 { get; set; }
        public string user_source2 { get; set; }
        public string add_by { get; set; }
        public Nullable<System.DateTime> add_date { get; set; }
        public string editby { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string note { get; set; }
        public string comp_code { get; set; }

        //Added by Priya
        public string doc_type { get; set; }
        public string doc_cat { get; set; }
        public string ref_type { get; set; }
        public string ref_no { get; set; }
        public string sch_time { get; set; }
        public Nullable<int> ContInfoId { get; set; }
        public string sch_by { get; set; }
        public string EmpId { get; set; }
        public string sch_rec_by_cd { get; set; }
        public string remark { get; set; }
        public string fin_year { get; set; }
        public string posting_period { get; set; }
        public string ref_doc_no { get; set; }
        public string ref_doc_type { get; set; }
        public string ref_doc_cat { get; set; }
        public Nullable<System.DateTime> ref_doc_date { get; set; }
        public Nullable<int> del_address { get; set; }
        public string status_remark { get; set; }
        public string t_display { get; set; }

    }
    public partial class PUR_T004_B
    {
        public int id { get; set; }
        public string sch_no { get; set; }
        public int line_id { get; set; }
        public string del_rel { get; set; }
        public string sales_order_no { get; set; }
        public string ref_no { get; set; }
        public string unit_code { get; set; }
        public string po_no { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<System.DateTime> expected_date { get; set; }
        public Nullable<decimal> confirm_qty { get; set; }
        public Nullable<System.DateTime> confirm_date { get; set; }
        public Nullable<System.DateTime> dispatch_date { get; set; }
        public Nullable<decimal> rec_qty { get; set; }
        public Nullable<System.DateTime> rec_date { get; set; }
        public string note { get; set; }
        public string t_status { get; set; }
        public string location_Id { get; set; }
        public Nullable<bool> active { get; set; }
        public string user_source1 { get; set; }
        public string user_source2 { get; set; }
        public string add_by { get; set; }
        public System.DateTime add_date { get; set; }
        public string editby { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string sku { get; set; }
        public string comp_code { get; set; }
        public Nullable<decimal> rate { get; set; }
        public string po_req_no { get; set; }
        public string ItemName { get; set; }

        //Added by Priya
        public string sch_cat { get; set; }
        public Nullable<int> po_item_row_id { get; set; }
        public string remark { get; set; }
        public string desp_id { get; set; }
        public string sku_desc { get; set; }
        public string fin_year { get; set; }
        public string posting_period { get; set; }
        public string rel_delivery { get; set; }
        public string rel_billing { get; set; }
        public Nullable<int> so_item_id { get; set; }
        public Nullable<decimal> order_qty { get; set; }
        public string confirm_status { get; set; }
        public Nullable<bool> del_block { get; set; }
        public string mov_tp { get; set; }
        public Nullable<System.DateTime> sch_date { get; set; }
        public string ship_mode { get; set; }
        public string PartyId { get; set; }
        public string para1 { get; set; }
        public string para2 { get; set; }
        public string para3 { get; set; }
        public string ref_doc_no { get; set; }
        public string ref_doc_type { get; set; }
        public string ref_doc_cat { get; set; }
        public Nullable<System.DateTime> ref_doc_date { get; set; }
        public string status_remark { get; set; }
        public Nullable<decimal> bal_qty { get; set; }

        public Nullable<int> pur_req_item_row_id { get; set; }
        public string sob_no { get; set; }
        public Nullable<decimal> qty_delivered { get; set; }
        public Nullable<int> sob_row_id { get; set; }
        public string bom_exp_no { get; set; }
        public string bom_no { get; set; }
        public string budget_no { get; set; }
        public string req_budget { get; set; }
        public string t_display { get; set; }
        public string tr_mode { get; set; }
        public string tr_type { get; set; }
        public string transportar_cd { get; set; }
        public string client { get; set; }
        public string contact_person_party { get; set; }
        public string schedule_by { get; set; }
        public string del_address_id { get; set; }
        public string bill_address_id { get; set; }
        public Nullable<int> req_sch_row_id { get; set; }
        public decimal? lead_time { get; set; }
        public string lead_uom { get; set; }
        public string price_qty_uom { get; set; }
        public decimal? price_qty { get; set; }
        public decimal? qty_price { get; set; }
        public string tr_party { get; set; }
        public string tr_name { get; set; }
        public int? item_line_id { get; set; }
        public string add_code_del { get; set; }
        public string add_code_bil { get; set; }

    }
    public class RptPUR_T002_B
    {

        public string po_no { get; set; }
        public string ItemCode { get; set; }
        public string description { get; set; }
        public string sku { get; set; }
        public string sku_desc { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string unit_code { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public string t_status { get; set; }
        public string comp_code { get; set; }
        public string location_Id { get; set; }
        public Nullable<bool> active { get; set; }
        public string symbol { get; set; }
        public string Mat_Condition { get; set; }
        public string Type { get; set; }
        public string Make { get; set; }
        public string hs_code { get; set; }
        public string hsn_code { get; set; }
        public string hsn_code2 { get; set; }
        //GST
        public string hs_code2 { get; set; }
        public string textdata { get; set; }
        public string t_display { get; set; }
        public string del_address_id { get; set; }

    }
}