using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Reflection.EF.SCM
{
    public partial class LOG_T001_A : ObjectBase
    {
        public int id { get; set; }
        public string delivery_no { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public string del_time { get; set; }
        public string PartyId { get; set; }
        public string ship_to_party { get; set; }
        public string notify_party { get; set; }
        public string order_no { get; set; }
        public string delivery_type { get; set; }
        public string doc_type { get; set; }
        public string doc_cat { get; set; }
        public Nullable<System.DateTime> pick_date { get; set; }
        public string pick_time { get; set; }
        public string shipment_mode { get; set; }
        public string transporter_party { get; set; }
        public string ladding_bill { get; set; }
        public Nullable<System.DateTime> ladding_date { get; set; }
        public Nullable<decimal> wt_goods { get; set; }
        public Nullable<decimal> net_weight { get; set; }
        public Nullable<decimal> net_wt { get; set; }
        public Nullable<decimal> gross_wt { get; set; }
        public Nullable<decimal> volume { get; set; }
        public string weight_unit { get; set; }
        public string volume_unit { get; set; }
        public Nullable<int> no_of_packages { get; set; }
        public Nullable<System.DateTime> loading_datetime { get; set; }
        public string cost_center { get; set; }
        public string profit_center { get; set; }
        public Nullable<decimal> net_value { get; set; }
        public Nullable<decimal> round_up { get; set; }
        public string curr_code { get; set; }
        public Nullable<decimal> exchange_rate { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public string slip_no { get; set; }
        public string tz_del_loc { get; set; }
        public string tz_rec_loc { get; set; }
        public string delivery_status { get; set; }
        public string so_code { get; set; }
        public string dc_code { get; set; }
        public string div_code { get; set; }
        public string soff_code { get; set; }
        public string sg_code { get; set; }
        public string bus_area { get; set; }
        public Nullable<bool> goods_issue { get; set; }
        public Nullable<System.DateTime> goods_issue_date { get; set; }
        public string bill_doc { get; set; }
        public string description { get; set; }
        public string t_status { get; set; }
        public string comp_code { get; set; }
        public string location_Id { get; set; }
        public string wa_code { get; set; }
        public string store_code { get; set; }
        public Nullable<bool> active { get; set; }
        public string add_by { get; set; }
        public System.DateTime add_date { get; set; }
        public string editby { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string mov_tp { get; set; }
        public string mov_tpw { get; set; }
        public Nullable<System.DateTime> act_move { get; set; }
        public string del_block { get; set; }
        public string bill_block { get; set; }
        public Nullable<System.DateTime> bill_date { get; set; }
        public Nullable<System.DateTime> pod_date { get; set; }
        public string incoterms { get; set; }
        public string incoterm2 { get; set; }
        public string rec_plant { get; set; }
        public string ref_docno { get; set; }
        public string ref_doc_type { get; set; }
        public string ref_doc_cat { get; set; }
        public string ship_status { get; set; }
        public string insp_status { get; set; }
        public string pre_carrage { get; set; }
        public string pre_carrage_place { get; set; }
        public string country_code { get; set; }
        public string port_load { get; set; }
        public string port_desc { get; set; }
        public string port_final { get; set; }
        public string final_dest { get; set; }
        public string ship_terms { get; set; }
        public string cf_agent_code { get; set; }
        public string lic_cod { get; set; }
        public string advance_lic { get; set; }
        public string origion_country { get; set; }
        public string pack_rem { get; set; }
        public string ship_mark { get; set; }
        public string vess_flight { get; set; }
        public string cntrl_no { get; set; }
        public string packing_no { get; set; }
        public Nullable<int> bill_address_id { get; set; }
        public Nullable<int> del_address { get; set; }
        public string KindOfPkgs { get; set; }
        public string marksAndNos { get; set; }
        public Nullable<bool> road_permit { get; set; }
        public string permit_no { get; set; }
        public Nullable<System.DateTime> permit_date { get; set; }
        public string fin_year { get; set; }
        public string posting_period { get; set; }
        public string del_desc { get; set; }
        public string soldpartynm { get; set; }
        public string shippartynm { get; set; }
        public string transporternm { get; set; }
        public string dest_countrynm { get; set; }
        public string cf_agentnm { get; set; }
        public string epcgnm { get; set; }
        public string adv_lic_nm { get; set; }
        public string countrynm { get; set; }
        public string sales_orgnm { get; set; }
        public string dcnm { get; set; }
        public string divnm { get; set; }
        public string sales_offnm { get; set; }
        public string sgnm { get; set; }
        public string currnm { get; set; }
        public string bill_addloc { get; set; }
        public string del_addloc { get; set; }
        public string supplantnm { get; set; }
        public string recplantnm { get; set; }
        public string EmpId { get; set; }
        public string ContPersnNm { get; set; }
        public string PersnEmailId { get; set; }
        public string PersnPhNo { get; set; }
        public string yr_ref_no { get; set; }
        public Nullable<System.DateTime> yr_ref_date { get; set; }
        public string doc_history_no { get; set; }
        public string status_remark { get; set; }
        public string rec_info { get; set; }
        public string lang_key { get; set; }
        public string bom_no { get; set; }
        public string data1 { get; set; }
        public string PrintOption { get; set; }
        public string tr_mode { get; set; }
        public string tr_type { get; set; }
        public string tr_party { get; set; }
        //scaler
        public string EmpName { get; set; }
        public string t_display { get; set; }
        public string add_info { get; set; }
        public string way_bill_no { get; set; }
        public Nullable<System.DateTime> way_bill_date { get; set; }
        public Nullable<decimal> way_bill_value { get; set; }
        public string add_code_del { get; set; }
        public string add_code_bil { get; set; }
        public string add_del { get; set; } // delivery address
        public string doc_type_name { get; set; }
    }
    public partial class LOG_T001_B
    {
        public Nullable<System.DateTime> cust_po_date;
        public string cust_po_no;
        public int id { get; set; }
        public string delivery_no { get; set; }
        public string sono { get; set; }
        public int line_id { get; set; }
        public string item_cat { get; set; }
        public string ItemCode { get; set; }
        public string Item_desc { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string unit_code { get; set; }
        public string insp_lot { get; set; }
        public string Partial_lot_no { get; set; }
        public string batch_no { get; set; }
        public Nullable<bool> goods_issue { get; set; }
        public string bill_doc { get; set; }
        public string description { get; set; }
        public decimal? gross_wt { get; set; }
        public decimal? net_wt { get; set; }
        public string weight_unit { get; set; }
        public Nullable<decimal> volume { get; set; }
        public string volumeunit { get; set; }
        public string volume_unit { get; set; }
        public Nullable<bool> split_allowed { get; set; }
        public Nullable<bool> block { get; set; }
        public string cost_center { get; set; }
        public string so_item_code { get; set; }
        public Nullable<decimal> convesion_factor { get; set; }
        public Nullable<decimal> net_price { get; set; }
        public string curr_code { get; set; }
        public string t_status { get; set; }
        public string comp_code { get; set; }
        public string location_Id { get; set; }
        public string wa_code { get; set; }
        public string store_code { get; set; }
        public string storage_bin { get; set; }
        public string sku { get; set; }
        public string sku_desc { get; set; }
        public string mov_tp { get; set; }
        public string mov_tpw { get; set; }
        public string batch_no_ven { get; set; }
        public string org_doc { get; set; }
        public string origion_item { get; set; }
        public string doc_cat { get; set; }
        public string profit_center { get; set; }
        public string order_no { get; set; }
        public string order_item_code { get; set; }
        public string ref_doc { get; set; }
        public string ref_doc_item_code { get; set; }
        public string ref_doc_type { get; set; }
        public Nullable<bool> relv_billing { get; set; }
        public string int_art { get; set; }
        public string cons_post { get; set; }
        public Nullable<decimal> net_value { get; set; }
        public string sch_no { get; set; }
        public string mov_ind { get; set; }
        public string reciss_item { get; set; }
        public string reciss_plant { get; set; }
        public string reciss_sl { get; set; }
        public string reciss_batch { get; set; }
        public string glacc { get; set; }
        public Nullable<System.DateTime> mfg_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public string ref_doc2 { get; set; }
        public string ref_doc_itemno { get; set; }
        public Nullable<int> reason { get; set; }
        public string del_cat { get; set; }
        public string pod_ind { get; set; }
        public string pod_con { get; set; }
        public string stock_trns { get; set; }
        public string del_copm { get; set; }
        public string ret_valid_from { get; set; }
        public string ret_valid_to { get; set; }
        public string country_code { get; set; }
        public string grade { get; set; }
        public string para1 { get; set; }
        public string para2 { get; set; }
        public string para3 { get; set; }
        public string para4 { get; set; }
        public string para5 { get; set; }
        public string marks { get; set; }
        public string container_no { get; set; }
        public Nullable<int> NoOfPkgs { get; set; }
        public string KindOfPkgs { get; set; }
        public Nullable<bool> active { get; set; }
        public string user_source1 { get; set; }
        public string user_source2 { get; set; }
        public string add_by { get; set; }
        public System.DateTime add_date { get; set; }
        public string editby { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string fin_year { get; set; }
        public string posting_period { get; set; }
        public string bom_no { get; set; }
        public string tr_mode { get; set; }
        public string status_remark { get; set; }
        public string gl_code { get; set; }
        public string lang_key { get; set; }
        public string client { get; set; }
        public Nullable<System.DateTime> goods_issue_date { get; set; }
        public int so_item_line_id { get; set; }
        public int so_item_row_id { get; set; }
        public int ref_item_line_id { get; set; }
        public int ref_item_row_id { get; set; }
        public int sch_item_row_id { get; set; }
        public int? order_item_row_id { get; set; }
        public int? grn_item_row_id { get; set; }
        public int? to_item_row_id { get; set; }
        public string order_doc_cat { get; set; }
        public string ref_doc_cat { get; set; }
        public string SubCatCode { get; set; }
        public Nullable<bool> StockUnt { get; set; }
        public string textdata { get; set; }
        public string t_display { get; set; }
        public string ind_batch_req { get; set; }

        //Scaler
        public string item_cat_code { get; set; } // Material Category
    }
    public partial class LOG_T001_C
    {
        public int id { get; set; }
        public string delivery_no { get; set; }
        public string ItemCode { get; set; }
        public string sku { get; set; }
        public string barcode { get; set; }
        public string pack_no { get; set; }
        public string batch_no { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string unit_code { get; set; }
        public string description { get; set; }
        public string t_status { get; set; }
        public string location_Id { get; set; }
        public string wa_code { get; set; }
        public string store_code { get; set; }
        public Nullable<bool> active { get; set; }
        public string add_by { get; set; }
        public System.DateTime add_date { get; set; }
        public string editby { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string comp_code { get; set; }
        public string ink_id { get; set; }
        public string ild_id { get; set; }
        public string grade { get; set; }
        public decimal? net_wt { get; set; }
        public decimal? gross_wt { get; set; }
        public string fin_year { get; set; }
        public string posting_period { get; set; }
        public string Ink { get; set; }
        public string Ild { get; set; }
        public string t_display { get; set; }
        public string client { get; set; }
        public int del_item_row_id { get; set; }
        public int line_id { get; set; }
    }
}
