using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Reflection.EF.CRM.ReportEntityCRM
{
    public class RptSalesInvoice : ObjectBase
    {
        public string bill_doc { get; set; }
        public string ship_cnd { get; set; }
        public Nullable<DateTime> bill_date { get; set; }
        public string incoterms { get; set; }
        public string curr_code { get; set; }
        public string p_term_code { get; set; }
        public string PartyId { get; set; }
        public string amt_word { get; set; }
        public string acc_code { get; set; }
        public string cust_acc { get; set; }
        public string ProdNmCd { get; set; }
        public string ProdNm { get; set; }
        public string bank_code { get; set; }
        public string bank_name { get; set; }
        public string trans_mode { get; set; }
        public string pre_carrage { get; set; }
        public string pre_carrage_place { get; set; }
        public string destNm { get; set; }
        public string port_load { get; set; }
        public string port_desc { get; set; }
        public string port_final { get; set; }
        public string final_dest { get; set; }
        public string ship_terms { get; set; }
        public string advance_lic { get; set; }
        public string lic_cod { get; set; }
        public string orgNm { get; set; }
        public string pack_rem { get; set; }
        public string ship_mark { get; set; }
        public string vess_flight { get; set; }
        public string description { get; set; }
        public string account_no { get; set; }
        public string swift_code { get; set; }
        public Nullable<int> bill_address_id { get; set; }
        public string shipping_mark { get; set; }
        public string insurance { get; set; }
        public string packing { get; set; }
        public string transhipment { get; set; }
        public string partshipment { get; set; }
        public Nullable<DateTime> shipment_date { get; set; }
        public Nullable<DateTime> add_date { get; set; }
        public Nullable<DateTime> validity_date { get; set; }
        public string payment_mode { get; set; }
        public string buyerNm { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string city1 { get; set; }
        public string state_code { get; set; }
        public string StatName { get; set; }
        public string country_code { get; set; }
        public string CntryName { get; set; }
        public string PinCode { get; set; }
        public string branch { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string acc_number { get; set; }
        public string zip { get; set; }
        public string ifsccode { get; set; }
        public string MICR_code { get; set; }
        public string cust_ref { get; set; }
        public Nullable<DateTime> cust_ref_date { get; set; }
        public string ref_doc_no { get; set; }
        public Nullable<DateTime> ref_doc_date { get; set; }
        public Nullable<DateTime> lic_dt { get; set; }
        public Nullable<decimal> qty_tol { get; set; }
        public Nullable<decimal> amt_tol { get; set; }
        public Nullable<DateTime> adv_date { get; set; }
        public string consignee { get; set; }
        public string hs_code { get; set; }
        public string hsn_code { get; set; }
        public string hsn_code2 { get; set; }
        public string bin_no { get; set; }
        public string wire { get; set; }
        public string ball { get; set; }
        public string doc_desc_user { get; set; }
        public string delivery_no { get; set; }
        public Nullable<DateTime> delivery_date { get; set; }
        public string transporter { get; set; }
        public string delivery_add { get; set; }
        public string form_type { get; set; }
        public Nullable<decimal> round_up { get; set; }
        public string lr_no { get; set; }
        public Nullable<DateTime> lr_date { get; set; }
        public Nullable<decimal> fright_values { get; set; }
        public string VATNo { get; set; }
        public Nullable<DateTime> VATDate { get; set; }
        public string CSTNo { get; set; }
        public Nullable<DateTime> CSTDate { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public Nullable<decimal> roundup_total { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> invoice_amt { get; set; }
        public Nullable<decimal> ass_value { get; set; }
        public Nullable<DateTime> doc_date { get; set; }
        public Nullable<DateTime> post_date { get; set; }
        public string service_tax_no { get; set; }
        public string PanNo { get; set; }
        public string VendorCd { get; set; }
        public string Customer_pono { get; set; }
        public Nullable<DateTime> po_date  { get; set; }
        public Nullable<DateTime> edit_date { get; set; }
        public string Seller { get; set; }
        public string SellerEmailId { get; set; }
        public string SellerMobNo { get; set; }
        public string doc_desc { get; set; }
        public string transporter_name { get; set; }
        public byte[] authorised_signature { get; set; }
        public string party_name { get; set; }
        public string bankStateNm { get; set; }
        public string bankCountryNm { get; set; }
        public string doc_type { get; set; }
        public string notify_party { get; set; }
        public string notify_nm { get; set; }
        public string notify_ph { get; set; }
        public string notify_address { get; set; }
        public string PhNo { get; set; }
        public string FaxNo { get; set; }
        public string consgn_ph { get; set; }
        public string consgn_fax { get; set; }
        public string inco_desc { get; set; }
        public string invoice_details { get; set; }
        public string lc_cond { get; set; }
        public Nullable<DateTime> ref_date { get; set; }
        public string EmailId { get; set; }
        public string PCSTNo { get; set; }
        public string PVATNo { get; set; }
        public string PSTNo { get; set; }
        public string PPanNo { get; set; }
        public string buyer_name { get; set; }
        public string buss_place { get; set; }
        public string stock_code { get; set; }
        public string doc_no { get; set; }
        public string no_of_packages { get; set; }
        public string ship_markL { get; set; }
        public string user_source1 { get; set; }
        public string incoterm2 { get; set; }
        public string symbol { get; set; }
        public string ref_data { get; set; }
        public string ref_data2 { get; set; }
        public Nullable<decimal> net_wt { get; set; }
        public decimal? gross_wt { get; set; }
        public string awb_no { get; set; }
        public Nullable<DateTime> awb_date { get; set; }
        public string custom_no { get; set; }
        public Nullable<DateTime> custom_date { get; set; }
        public string terms_of_delivery { get; set; }
        public string manual_item_desc { get; set; }
        public string manual_desc { get; set; }
        public string proforma_no { get; set; }
        public Nullable<DateTime> proforma_date { get; set; }
        public string duty_drawback { get; set; }
        public Nullable<decimal> export_commision { get; set; }
        public Nullable<decimal> export_commision_val { get; set; }
        public string meis { get; set; }
        public string lc_info { get; set; }
        public string LoctnNm { get; set; }
        public string AddL1 { get; set; }
        public string AddL2 { get; set; }
        public string cityL { get; set; }
        public string stateNmL { get; set; }
        public string STP_gstinno { get; set; }
        public string DTP_gstinno { get; set; }
        public Nullable<System.DateTime> STP_gstindate { get; set; }
        public Nullable<System.DateTime> DTP_gstindate { get; set; }
        public string STP_state_code { get; set; }
        public string DTP_state_code { get; set; }
        public string data1 { get; set; }
        public string owner_name { get; set; }
        public string DEmp_PhNo { get; set; }
        public string DEmp_FaxNo { get; set; }
        public string DEmp_EmailId { get; set; }
        public string status_remark { get; set; }
        public string amt_word_tax { get; set; }
        public string declaration { get; set; }
        public string payer_nm { get; set; }
        public string payer_address { get; set; }
        public string tax_declaration { get; set; }
        public Nullable<decimal> wt_gross { get; set; }
        public Nullable<decimal> wt_net { get; set; }
        public string unit_code { get; set; }
        public string ad_code { get; set; }
        public string dec_desc { get; set; }
        public string dec_code { get; set; }
        public string rex_no { get; set; }
        public string end_use_code { get; set; }
        public string reg_declaration { get; set; }
        public string reg_no { get; set; }
        public string notify_party_name2 { get; set; }
        public string notify_address2 { get; set; }
        public string weight_unit { get; set; }
        public string tr_name { get; set; }
        public string ref_incoterms { get; set; }
        public string ref_roundup_total { get; set; }
        public Nullable<decimal> exc_rate { get; set; }
        public Nullable<decimal> ref_exc_rate { get; set; }
        public Nullable<decimal> net_value_wo_tax_item { get; set; }
        public string awb_inst { get; set; }
        public string vendor_remark { get; set; }
        public Nullable<DateTime> del_date { get; set; }
        public string DeptName { get; set; }
        public string PersnEmailId { get; set; }
        public string ref_declaration { get; set; }
        public string PersnMobNo { get; set; }
        public string para5 { get; set; }
        public string para9 { get; set; }
        public string acc_no { get; set; }
        public string acc_name { get; set; }
        public string location_id { get; set; }
        public string location_id_reg { get; set; }//Registered Location from Company Master
        public string contract_acc { get; set; }
        public string lic_name { get; set; }
        public string amt_word_local { get; set; }
        public DateTime? rev_date { get; set; }
    }

    public class RptSalesInvoiceItem
    {
        public string ItemCode { get; set; }
        public string item_desc { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<decimal> wt_gross { get; set; }
        public Nullable<decimal> wt_net { get; set; }
        public string unit_code { get; set; }
        public string marks { get; set; }
        public Nullable<int> NoOfPkgs { get; set; }
        public string container_no { get; set; }
        public string KindOfPkgs { get; set; }
        public string cust_cat_no { get; set; }
        public string CstmrItmCod { get; set; }
        public string CstmrItmDesc { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> discount_amt { get; set; }
        public string Remark { get; set; }
        public string ink { get; set; }
        public string ild { get; set; }
        public string grade_code { get; set; }
        public string textdata { get; set; }
        public string ref_doc_no { get; set; }
        public string ProdNm { get; set; }
        public string hs_code { get; set; }
        public string hsn_code { get; set; }
        public string hsn_code2 { get; set; }
        public string symbol { get; set; }
        public string delivery_no { get; set; }
        public Nullable<decimal> delivery_date { get; set; }
        public string hs_code2 { get; set; }
        public string sono { get; set; }
        public Nullable<System.DateTime> sodate { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public string wire_calc { get; set; }
        public string ball_calc { get; set; }    
        public string wire_Type { get; set; }
        public string wire_size { get; set; }
        public string ball_type { get; set; }
        public string ball_dia { get; set; }
        public Nullable<decimal> qty_price { get; set; }
        public Nullable<decimal> price_qty { get; set; }
        public string price_qty_uom { get; set; }
        public string weight_unit { get; set; }
        public decimal? gross_wt { get; set; }
        public decimal? net_wt { get; set; }
        public string cust_ref { get; set; }
        public string item_category { get; set; }
        public decimal? net_value { get; set; }
        public decimal? gross_value { get; set; }
        public decimal? effective_value { get; set; }
        public string batch_no { get; set; }
        public Nullable<decimal> exc_rate { get; set; }
        public string carton_count_from { get; set; }
        public string carton_count_to { get; set; }
    }
}

