using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Reflection.EF.Finance
{
    public partial class ACC_T002 : ObjectBase
    {
        public string doc_no { get; set; }
        public System.DateTime doc_date { get; set; }
        public string doc_cat { get; set; }
        public string doc_type { get; set; }
        public string PartyId { get; set; }
        public string PartyId1 { get; set; }
        public Nullable<decimal> credit { get; set; }
        public Nullable<decimal> debit { get; set; }
        public string ref_doc_no { get; set; }
        public string ref_doc_no1 { get; set; }
        public Nullable<System.DateTime> ref_doc_date { get; set; }
        public Nullable<System.DateTime> ref_doc_date1 { get; set; }
        public string ref_doc_type { get; set; }
        public string ref_doc_type1 { get; set; }
        public string local_currency { get; set; }
        public string local_currency2 { get; set; }
        public string local_currency3 { get; set; }
        public Nullable<decimal> exc_rate { get; set; }
        public Nullable<decimal> exc_rate_curr2 { get; set; }
        public Nullable<decimal> exc_rate_curr3 { get; set; }
        public string exch_rate_type { get; set; }
        public string exch_rate_type2 { get; set; }
        public Nullable<decimal> exc_rate_tax { get; set; }
        public string analysis_code { get; set; }
        public string cost_center { get; set; }
        public string gl_amt_extax { get; set; }
        public string source_comp { get; set; }
        public Nullable<System.DateTime> inv_reciept_date { get; set; }
        public string src_curr { get; set; }
        public string trans_datetp_sec_curr { get; set; }
        public string curr_type_sec { get; set; }
        public string trans_datetp_thir_curr { get; set; }
        public string curr_type_thir { get; set; }
        public string entry_time { get; set; }
        public Nullable<System.DateTime> doc_add_date { get; set; }
        public string ind_doc_posted { get; set; }
        public decimal? group_exch_rate { get; set; }
        public string grp_curr_code { get; set; }
        public string curr_code { get; set; }
        public Nullable<System.DateTime> post_date { get; set; }
        public string gl_code { get; set; }
        public string gl_code1 { get; set; }
        public string PartyNm { get; set; }
        public string PartyNm1 { get; set; }
        public string gl_subgrp { get; set; }
        public string gl_grp { get; set; }
        public string fin_year { get; set; }
        public string posting_period { get; set; }
        public string t_status { get; set; }
        public bool active { get; set; }
        public string lang_key { get; set; }
        public string comp_code { get; set; }
        public string location_Id { get; set; }
        public string add_by { get; set; }
        public System.DateTime add_date { get; set; }
        public string editby { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string remark { get; set; }
        public string note { get; set; }
        public decimal? doc_curr_amt { get; set; }
        public decimal? loc_curr_amt { get; set; }
        public string tranCode { get; set; }
        public string JE_type { get; set; }
        public string dc_ind { get; set; }
        public string bank_no_payee { get; set; }
        public string party_ref_no { get; set; }
        public string posting_key { get; set; }
        public string acc_type { get; set; }
        public string ledger_gen { get; set; }

        #region Scalar Variables ACC_T002
        public string XmlDataDocument_FlipGrid { get; set; }
        public string XmlDataDocument_ACC_T002_A { get; set; }
        public string curr_name { get; set; }
        public string JE_desc { get; set; }
        public Nullable<decimal> AmntToBeCredited { get; set; }
        public string PayeeBankName { get; set; }
        public string t_display { get; set; }
        public string gl_name { get; set; }

        #endregion
    }
    public partial class ACC_T002_A
    {
        public int id { get; set; }
        public string doc_no { get; set; }
        public int line_id { get; set; }
        public Nullable<int> no_of_line { get; set; }
        public Nullable<int> item_identity { get; set; }
        public Nullable<System.DateTime> clrg_date { get; set; }
        public Nullable<System.DateTime> clrg_entry_date { get; set; }
        public string clrg_doc_no { get; set; }
        public string posting_key { get; set; }
        public string acc_type { get; set; }
        public string gl_code { get; set; }
        public string ledger_gen { get; set; }
        public string ind_gl { get; set; }
        public string sp_gltype { get; set; }
        public string curr_code { get; set; }
        public Nullable<decimal> exc_rate { get; set; }
        public string local_curr_code { get; set; }
        public string dc_ind { get; set; }
        public Nullable<decimal> doc_curr_amt { get; set; }
        public Nullable<decimal> loc_curr_amt { get; set; }
        public string analysis_code { get; set; }
        public string cost_center { get; set; }
        public string tax_code { get; set; }
        public Nullable<decimal> amt_loc_taxbase { get; set; }
        public Nullable<decimal> amt_doc_taxbase { get; set; }
        public Nullable<decimal> amt_tax_local_curr { get; set; }
        public Nullable<decimal> amt_tax_doc_curr { get; set; }
        public Nullable<decimal> amt_taxbase_local_curr { get; set; }
        public Nullable<decimal> amt_taxbase_doc_curr { get; set; }
        public string ds_cash { get; set; }
        public Nullable<decimal> amt_withhold_tax { get; set; }
        public Nullable<decimal> headge_rate { get; set; }
        public Nullable<decimal> amt_headge { get; set; }
        public Nullable<decimal> value_diff { get; set; }
        public Nullable<decimal> value_diff_sec_curr { get; set; }
        public string assign_no { get; set; }
        public string item_text { get; set; }
        public string expt_int { get; set; }
        public string group_acc_no { get; set; }
        public string gl_trns_type { get; set; }
        public string PartyId { get; set; }
        public string vendor_no { get; set; }
        public string ind_bal_sheet { get; set; }
        public string pl_acctype { get; set; }
        public string gl_assign { get; set; }
        public string plan_level { get; set; }
        public string plan_group { get; set; }
        public Nullable<decimal> amt_plan { get; set; }
        public Nullable<System.DateTime> plan_date { get; set; }
        public string budget_item { get; set; }
        public string control_area { get; set; }
        public string order_no { get; set; }
        public string bill_doc { get; set; }
        public string sales_doc { get; set; }
        public Nullable<int> sales_doc_item { get; set; }
        public Nullable<int> del_sch_lineno { get; set; }
        public string main_asset_no { get; set; }
        public string asse_subno { get; set; }
        public string asset_trns_type { get; set; }
        public Nullable<System.DateTime> asset_value_date { get; set; }
        public Nullable<decimal> cash_disc1 { get; set; }
        public Nullable<decimal> cash_disc2 { get; set; }
        public string payterm_key { get; set; }
        public Nullable<decimal> payterm_period { get; set; }
        public Nullable<decimal> disc_per1 { get; set; }
        public Nullable<decimal> disc_per2 { get; set; }
        public Nullable<decimal> amt_cd_eligible { get; set; }
        public Nullable<decimal> cd_loc_curr { get; set; }
        public Nullable<decimal> cd_doc_curr { get; set; }
        public string pay_method { get; set; }
        public string pay_block_key { get; set; }
        public string fix_payterm { get; set; }
        public string hb_key { get; set; }
        public string partner_bank_type { get; set; }
        public decimal? net_pay_amt { get; set; }
        public string tax_code_dist { get; set; }
        public decimal? amt_taxdist_local_curr { get; set; }
        public decimal? amt_taxdist_for_curr { get; set; }
        public int? no_of_inv { get; set; }
        public string fin_year_inv { get; set; }
        public int? line_item_inv { get; set; }
        public string ex_bill_no { get; set; }
        public string ex_bill_finyear { get; set; }
        public int? ex_bill_line { get; set; }
        public string ex_bill_usage { get; set; }
        public string ex_bill_doc { get; set; }
        public string ex_bill_req { get; set; }
        public string ex_bill_comp { get; set; }
        public DateTime? ex_bill_duedate { get; set; }
        public string ItemCode { get; set; }
        public string plant_code { get; set; }
        public decimal? qty { get; set; }
        public string unit_code { get; set; }
        public decimal? qty_unit { get; set; }
        public decimal? qty_pur { get; set; }
        public decimal? order_price { get; set; }
        public string po_no { get; set; }
        public int? po_item_no { get; set; }
        public int? seq_assign { get; set; }
        public string ind_delivery { get; set; }
        public string base_unit { get; set; }
        public decimal? price_unit { get; set; }
        public string value_type { get; set; }
        public decimal? inv_val_loc { get; set; }
        public decimal? inv_val_for { get; set; }
        public decimal? amt_qual_loc { get; set; }
        public string block_price { get; set; }
        public string block_qty { get; set; }
        public string block_date { get; set; }
        public string block_orderpriceqty { get; set; }
        public string block_project { get; set; }
        public string block_manual { get; set; }
        public string vat_no { get; set; }
        public string dest_country { get; set; }
        public string country_code { get; set; }
        public string reason_code { get; set; }
        public decimal? ex_rate_rea { get; set; }
        public decimal? ex_rate_diff { get; set; }
        public string profit_center { get; set; }
        public string gl_assign_man { get; set; }
        public string equity_group { get; set; }
        public string tax_jurisdiction { get; set; }
        public string payroll_type { get; set; }
        public string payee_payer { get; set; }
        public int? inst1 { get; set; }
        public int? inst2 { get; set; }
        public string client { get; set; }
        public string comp_code { get; set; }
        public string location_Id { get; set; }
        public string fin_year { get; set; }
        public string posting_period { get; set; }
        public string add_by { get; set; }
        public System.DateTime add_date { get; set; }
        public string editby { get; set; }
        public DateTime? edit_date { get; set; }
        public string Remark { get; set; }
        public bool? active { get; set; }
        public string t_status { get; set; }
        public string user_source1 { get; set; }
        public string user_source2 { get; set; }
        public string doc_cat { get; set; }
        public string doc_type { get; set; }
        public DateTime doc_date { get; set; }
        public string ref_doc_no { get; set; }
        public string ref_doc_type { get; set; }
        public string ref_doc_cat { get; set; }
        public int analytical_id { get; set; }
        public decimal? debit_amt { get; set; }
        public decimal? credit_amt { get; set; }
        public decimal? balance_amt { get; set; }
        public string TranCode { get; set; }
        public decimal? amt_residual { get; set; }
        public string amt_residual_curr { get; set; }
        public bool? reconcile { get; set; }
        public string party_ref_no { get; set; }
        public string cheque_no { get; set; }

        #region Scalar Variables ACC_T002_A
        public string PartyNm { get; set; }
        public string gl_name { get; set; }
        public string t_display { get; set; }
        #endregion

    }
}
