//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reflection.WebServices.Gateway.ReflectionWebExecuter {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFaultContract", Namespace="http://schemas.datacontract.org/2004/07/ReflectionServiceHost")]
    [System.SerializableAttribute()]
    public partial class ServiceFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CorrelationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid correlationId1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CorrelationId {
            get {
                return this.CorrelationIdField;
            }
            set {
                if ((this.CorrelationIdField.Equals(value) != true)) {
                    this.CorrelationIdField = value;
                    this.RaisePropertyChanged("CorrelationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorID {
            get {
                return this.ErrorIDField;
            }
            set {
                if ((this.ErrorIDField.Equals(value) != true)) {
                    this.ErrorIDField = value;
                    this.RaisePropertyChanged("ErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="correlationId")]
        public System.Guid correlationId1 {
            get {
                return this.correlationId1Field;
            }
            set {
                if ((this.correlationId1Field.Equals(value) != true)) {
                    this.correlationId1Field = value;
                    this.RaisePropertyChanged("correlationId1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReflectionWebExecuter.IReflectionService")]
    public interface IReflectionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/Insert", ReplyAction="http://tempuri.org/IReflectionService/InsertResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Reflection.WebServices.Gateway.ReflectionWebExecuter.ServiceFaultContract), Action="http://tempuri.org/IReflectionService/InsertServiceFaultContractFault", Name="ServiceFaultContract", Namespace="http://schemas.datacontract.org/2004/07/ReflectionServiceHost")]
        string Insert(string Request, string RequestOption, string Module, string strType, int intValue, string strValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/Insert", ReplyAction="http://tempuri.org/IReflectionService/InsertResponse")]
        System.Threading.Tasks.Task<string> InsertAsync(string Request, string RequestOption, string Module, string strType, int intValue, string strValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/InsertWithCompression", ReplyAction="http://tempuri.org/IReflectionService/InsertWithCompressionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Reflection.WebServices.Gateway.ReflectionWebExecuter.ServiceFaultContract), Action="http://tempuri.org/IReflectionService/InsertWithCompressionServiceFaultContractFa" +
            "ult", Name="ServiceFaultContract", Namespace="http://schemas.datacontract.org/2004/07/ReflectionServiceHost")]
        byte[] InsertWithCompression(byte[] RequestStream, string Request, string RequestOption, string RequestPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/InsertWithCompression", ReplyAction="http://tempuri.org/IReflectionService/InsertWithCompressionResponse")]
        System.Threading.Tasks.Task<byte[]> InsertWithCompressionAsync(byte[] RequestStream, string Request, string RequestOption, string RequestPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/Update", ReplyAction="http://tempuri.org/IReflectionService/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Reflection.WebServices.Gateway.ReflectionWebExecuter.ServiceFaultContract), Action="http://tempuri.org/IReflectionService/UpdateServiceFaultContractFault", Name="ServiceFaultContract", Namespace="http://schemas.datacontract.org/2004/07/ReflectionServiceHost")]
        string Update(string Request, string RequestOption, string Module, string strType, int intValue, string strValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/Update", ReplyAction="http://tempuri.org/IReflectionService/UpdateResponse")]
        System.Threading.Tasks.Task<string> UpdateAsync(string Request, string RequestOption, string Module, string strType, int intValue, string strValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/UpdateWithCompression", ReplyAction="http://tempuri.org/IReflectionService/UpdateWithCompressionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Reflection.WebServices.Gateway.ReflectionWebExecuter.ServiceFaultContract), Action="http://tempuri.org/IReflectionService/UpdateWithCompressionServiceFaultContractFa" +
            "ult", Name="ServiceFaultContract", Namespace="http://schemas.datacontract.org/2004/07/ReflectionServiceHost")]
        byte[] UpdateWithCompression(byte[] RequestStream, string Request, string RequestOption, string RequestPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/UpdateWithCompression", ReplyAction="http://tempuri.org/IReflectionService/UpdateWithCompressionResponse")]
        System.Threading.Tasks.Task<byte[]> UpdateWithCompressionAsync(byte[] RequestStream, string Request, string RequestOption, string RequestPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/DeleteWithString", ReplyAction="http://tempuri.org/IReflectionService/DeleteWithStringResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Reflection.WebServices.Gateway.ReflectionWebExecuter.ServiceFaultContract), Action="http://tempuri.org/IReflectionService/DeleteWithStringServiceFaultContractFault", Name="ServiceFaultContract", Namespace="http://schemas.datacontract.org/2004/07/ReflectionServiceHost")]
        string DeleteWithString(string Request, string RequestOption, string Module);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/DeleteWithString", ReplyAction="http://tempuri.org/IReflectionService/DeleteWithStringResponse")]
        System.Threading.Tasks.Task<string> DeleteWithStringAsync(string Request, string RequestOption, string Module);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/DeleteWithNumeric", ReplyAction="http://tempuri.org/IReflectionService/DeleteWithNumericResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Reflection.WebServices.Gateway.ReflectionWebExecuter.ServiceFaultContract), Action="http://tempuri.org/IReflectionService/DeleteWithNumericServiceFaultContractFault", Name="ServiceFaultContract", Namespace="http://schemas.datacontract.org/2004/07/ReflectionServiceHost")]
        string DeleteWithNumeric(int Request, string RequestOption, string Module);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/DeleteWithNumeric", ReplyAction="http://tempuri.org/IReflectionService/DeleteWithNumericResponse")]
        System.Threading.Tasks.Task<string> DeleteWithNumericAsync(int Request, string RequestOption, string Module);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/GetData", ReplyAction="http://tempuri.org/IReflectionService/GetDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Reflection.WebServices.Gateway.ReflectionWebExecuter.ServiceFaultContract), Action="http://tempuri.org/IReflectionService/GetDataServiceFaultContractFault", Name="ServiceFaultContract", Namespace="http://schemas.datacontract.org/2004/07/ReflectionServiceHost")]
        byte[] GetData(string Request, string RequestOption, string RequestPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/GetData", ReplyAction="http://tempuri.org/IReflectionService/GetDataResponse")]
        System.Threading.Tasks.Task<byte[]> GetDataAsync(string Request, string RequestOption, string RequestPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/GetDataWithCompression1", ReplyAction="http://tempuri.org/IReflectionService/GetDataWithCompression1Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(Reflection.WebServices.Gateway.ReflectionWebExecuter.ServiceFaultContract), Action="http://tempuri.org/IReflectionService/GetDataWithCompression1ServiceFaultContract" +
            "Fault", Name="ServiceFaultContract", Namespace="http://schemas.datacontract.org/2004/07/ReflectionServiceHost")]
        byte[] GetDataWithCompression1(string Request, string RequestOption, string Module, string strType, int intValue, string strValue, string doc_code, string comp_code, string location_Id, string add_by, string request1, string request2, string request3, string request4, string request5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/GetDataWithCompression1", ReplyAction="http://tempuri.org/IReflectionService/GetDataWithCompression1Response")]
        System.Threading.Tasks.Task<byte[]> GetDataWithCompression1Async(string Request, string RequestOption, string Module, string strType, int intValue, string strValue, string doc_code, string comp_code, string location_Id, string add_by, string request1, string request2, string request3, string request4, string request5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/GetDataWithCompression", ReplyAction="http://tempuri.org/IReflectionService/GetDataWithCompressionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Reflection.WebServices.Gateway.ReflectionWebExecuter.ServiceFaultContract), Action="http://tempuri.org/IReflectionService/GetDataWithCompressionServiceFaultContractF" +
            "ault", Name="ServiceFaultContract", Namespace="http://schemas.datacontract.org/2004/07/ReflectionServiceHost")]
        byte[] GetDataWithCompression(string Request, string RequestOption, string Module, string strType, int intValue, string strValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/GetDataWithCompression", ReplyAction="http://tempuri.org/IReflectionService/GetDataWithCompressionResponse")]
        System.Threading.Tasks.Task<byte[]> GetDataWithCompressionAsync(string Request, string RequestOption, string Module, string strType, int intValue, string strValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/UploadFiles", ReplyAction="http://tempuri.org/IReflectionService/UploadFilesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Reflection.WebServices.Gateway.ReflectionWebExecuter.ServiceFaultContract), Action="http://tempuri.org/IReflectionService/UploadFilesServiceFaultContractFault", Name="ServiceFaultContract", Namespace="http://schemas.datacontract.org/2004/07/ReflectionServiceHost")]
        byte[] UploadFiles(byte[] RequestStream, string Request, string RequestOption, string RequestPath, string FileName, string client, string comp_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/UploadFiles", ReplyAction="http://tempuri.org/IReflectionService/UploadFilesResponse")]
        System.Threading.Tasks.Task<byte[]> UploadFilesAsync(byte[] RequestStream, string Request, string RequestOption, string RequestPath, string FileName, string client, string comp_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/DownloadFiles", ReplyAction="http://tempuri.org/IReflectionService/DownloadFilesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Reflection.WebServices.Gateway.ReflectionWebExecuter.ServiceFaultContract), Action="http://tempuri.org/IReflectionService/DownloadFilesServiceFaultContractFault", Name="ServiceFaultContract", Namespace="http://schemas.datacontract.org/2004/07/ReflectionServiceHost")]
        byte[] DownloadFiles(string Request, string RequestOption, string RequestPath, string FileName, string client, string comp_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/DownloadFiles", ReplyAction="http://tempuri.org/IReflectionService/DownloadFilesResponse")]
        System.Threading.Tasks.Task<byte[]> DownloadFilesAsync(string Request, string RequestOption, string RequestPath, string FileName, string client, string comp_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/DeleteFiles", ReplyAction="http://tempuri.org/IReflectionService/DeleteFilesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Reflection.WebServices.Gateway.ReflectionWebExecuter.ServiceFaultContract), Action="http://tempuri.org/IReflectionService/DeleteFilesServiceFaultContractFault", Name="ServiceFaultContract", Namespace="http://schemas.datacontract.org/2004/07/ReflectionServiceHost")]
        string DeleteFiles(string Request, string RequestOption, string RequestPath, string FileName, string client, string comp_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectionService/DeleteFiles", ReplyAction="http://tempuri.org/IReflectionService/DeleteFilesResponse")]
        System.Threading.Tasks.Task<string> DeleteFilesAsync(string Request, string RequestOption, string RequestPath, string FileName, string client, string comp_code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReflectionServiceChannel : Reflection.WebServices.Gateway.ReflectionWebExecuter.IReflectionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReflectionServiceClient : System.ServiceModel.ClientBase<Reflection.WebServices.Gateway.ReflectionWebExecuter.IReflectionService>, Reflection.WebServices.Gateway.ReflectionWebExecuter.IReflectionService {
        
        public ReflectionServiceClient() {
        }
        
        public ReflectionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReflectionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReflectionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReflectionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Insert(string Request, string RequestOption, string Module, string strType, int intValue, string strValue) {
            return base.Channel.Insert(Request, RequestOption, Module, strType, intValue, strValue);
        }
        
        public System.Threading.Tasks.Task<string> InsertAsync(string Request, string RequestOption, string Module, string strType, int intValue, string strValue) {
            return base.Channel.InsertAsync(Request, RequestOption, Module, strType, intValue, strValue);
        }
        
        public byte[] InsertWithCompression(byte[] RequestStream, string Request, string RequestOption, string RequestPath) {
            return base.Channel.InsertWithCompression(RequestStream, Request, RequestOption, RequestPath);
        }
        
        public System.Threading.Tasks.Task<byte[]> InsertWithCompressionAsync(byte[] RequestStream, string Request, string RequestOption, string RequestPath) {
            return base.Channel.InsertWithCompressionAsync(RequestStream, Request, RequestOption, RequestPath);
        }
        
        public string Update(string Request, string RequestOption, string Module, string strType, int intValue, string strValue) {
            return base.Channel.Update(Request, RequestOption, Module, strType, intValue, strValue);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAsync(string Request, string RequestOption, string Module, string strType, int intValue, string strValue) {
            return base.Channel.UpdateAsync(Request, RequestOption, Module, strType, intValue, strValue);
        }
        
        public byte[] UpdateWithCompression(byte[] RequestStream, string Request, string RequestOption, string RequestPath) {
            return base.Channel.UpdateWithCompression(RequestStream, Request, RequestOption, RequestPath);
        }
        
        public System.Threading.Tasks.Task<byte[]> UpdateWithCompressionAsync(byte[] RequestStream, string Request, string RequestOption, string RequestPath) {
            return base.Channel.UpdateWithCompressionAsync(RequestStream, Request, RequestOption, RequestPath);
        }
        
        public string DeleteWithString(string Request, string RequestOption, string Module) {
            return base.Channel.DeleteWithString(Request, RequestOption, Module);
        }
        
        public System.Threading.Tasks.Task<string> DeleteWithStringAsync(string Request, string RequestOption, string Module) {
            return base.Channel.DeleteWithStringAsync(Request, RequestOption, Module);
        }
        
        public string DeleteWithNumeric(int Request, string RequestOption, string Module) {
            return base.Channel.DeleteWithNumeric(Request, RequestOption, Module);
        }
        
        public System.Threading.Tasks.Task<string> DeleteWithNumericAsync(int Request, string RequestOption, string Module) {
            return base.Channel.DeleteWithNumericAsync(Request, RequestOption, Module);
        }
        
        public byte[] GetData(string Request, string RequestOption, string RequestPath) {
            return base.Channel.GetData(Request, RequestOption, RequestPath);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetDataAsync(string Request, string RequestOption, string RequestPath) {
            return base.Channel.GetDataAsync(Request, RequestOption, RequestPath);
        }
        
        public byte[] GetDataWithCompression1(string Request, string RequestOption, string Module, string strType, int intValue, string strValue, string doc_code, string comp_code, string location_Id, string add_by, string request1, string request2, string request3, string request4, string request5) {
            return base.Channel.GetDataWithCompression1(Request, RequestOption, Module, strType, intValue, strValue, doc_code, comp_code, location_Id, add_by, request1, request2, request3, request4, request5);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetDataWithCompression1Async(string Request, string RequestOption, string Module, string strType, int intValue, string strValue, string doc_code, string comp_code, string location_Id, string add_by, string request1, string request2, string request3, string request4, string request5) {
            return base.Channel.GetDataWithCompression1Async(Request, RequestOption, Module, strType, intValue, strValue, doc_code, comp_code, location_Id, add_by, request1, request2, request3, request4, request5);
        }
        
        public byte[] GetDataWithCompression(string Request, string RequestOption, string Module, string strType, int intValue, string strValue) {
            return base.Channel.GetDataWithCompression(Request, RequestOption, Module, strType, intValue, strValue);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetDataWithCompressionAsync(string Request, string RequestOption, string Module, string strType, int intValue, string strValue) {
            return base.Channel.GetDataWithCompressionAsync(Request, RequestOption, Module, strType, intValue, strValue);
        }
        
        public byte[] UploadFiles(byte[] RequestStream, string Request, string RequestOption, string RequestPath, string FileName, string client, string comp_code) {
            return base.Channel.UploadFiles(RequestStream, Request, RequestOption, RequestPath, FileName, client, comp_code);
        }
        
        public System.Threading.Tasks.Task<byte[]> UploadFilesAsync(byte[] RequestStream, string Request, string RequestOption, string RequestPath, string FileName, string client, string comp_code) {
            return base.Channel.UploadFilesAsync(RequestStream, Request, RequestOption, RequestPath, FileName, client, comp_code);
        }
        
        public byte[] DownloadFiles(string Request, string RequestOption, string RequestPath, string FileName, string client, string comp_code) {
            return base.Channel.DownloadFiles(Request, RequestOption, RequestPath, FileName, client, comp_code);
        }
        
        public System.Threading.Tasks.Task<byte[]> DownloadFilesAsync(string Request, string RequestOption, string RequestPath, string FileName, string client, string comp_code) {
            return base.Channel.DownloadFilesAsync(Request, RequestOption, RequestPath, FileName, client, comp_code);
        }
        
        public string DeleteFiles(string Request, string RequestOption, string RequestPath, string FileName, string client, string comp_code) {
            return base.Channel.DeleteFiles(Request, RequestOption, RequestPath, FileName, client, comp_code);
        }
        
        public System.Threading.Tasks.Task<string> DeleteFilesAsync(string Request, string RequestOption, string RequestPath, string FileName, string client, string comp_code) {
            return base.Channel.DeleteFilesAsync(Request, RequestOption, RequestPath, FileName, client, comp_code);
        }
    }
}
