using System;

namespace Reflection.EF.QMS
{
    public partial class QMS_T001 : ObjectBase
    {
        public string doc_no { get; set; }
        public string doc_cat { get; set; }
        public string doc_type { get; set; }
        public string lab_code { get; set; }
        public string barcode { get; set; }
        public string test_code { get; set; }
        public string ref_doc_no { get; set; }
        public string rig_code { get; set; }
        public string tr_code { get; set; }
        public string temperature { get; set; }
        public string humidity { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public string master_inst { get; set; }
        public string EmpId { get; set; }
        public string cal_type { get; set; }
        public string po_no { get; set; }
        public string PartyId { get; set; }
        public int ContInfoId { get; set; }
        public DateTime? cal_date { get; set; }
        public DateTime? last_date { get; set; }
        public int cal_freq { get; set; }
        public string cal_period { get; set; }
        public DateTime? next_date { get; set; }
        public string u_remark1 { get; set; }
        public string u_remark2 { get; set; }
        public string u_remark3 { get; set; }
        public bool? active { get; set; }
        public string t_status { get; set; }
        public string add_by { get; set; }
        public DateTime add_date { get; set; }
        public string editby { get; set; }
        public DateTime? edit_date { get; set; }
        public string location_Id { get; set; }
        public string comp_code { get; set; }
        public string lang_key { get; set; }
        public string start_temp { get; set; }
        public string end_temp { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
        public DateTime? doc_date { get; set; }
        public DateTime? due_date { get; set; }
        public string PartyNm { get; set; }
        public string inst_code { get; set; }
        public string inst_name { get; set; }
        public string serv_type { get; set; }
        public string insp_lot_no { get; set; }
        public decimal? resolution { get; set; }
        public string middle_temp { get; set; }
        public string authEmpId { get; set; }
        public string siteEmpId { get; set; }
        //Scalar
        public string test_name { get; set; }
        public string inst_id { get; set; }
        public string inst_make { get; set; }
        public string inst_srno { get; set; }
        public string model_no { get; set; }
        public decimal? least_count { get; set; }
        public string range { get; set; }
        public decimal? accuracy_up { get; set; }
        public string cont_per_name { get; set; }
        public string EmpNm { get; set; }
        public string tr_name { get; set; }
        public string rig_name { get; set; }
        public string lab_name { get; set; }
        public string to_mail_id { get; set; }
        public string inst_cond { get; set; }
        public string authEmpNm { get; set; }
        public string authEmp_desig { get; set; }
        public string cust_name { get; set; }
        public string insp_cat { get; set; }
        public string wi_desc { get; set; }
        public string range_unit { get; set; }
        public string accuracy_up_unit { get; set; }
        public string least_count_unit { get; set; }
        public string resolution_unit { get; set; }
        public decimal? upper_range { get; set; }
        public decimal? lower_range { get; set; }
        public string upper_range_unit { get; set; }
        public string lower_range_unit { get; set; }
        public string siteEmpNm { get; set; }
        public decimal? accuracy_down { get; set; }
        public string accuracy_down_unit { get; set; }
        public string bill_address { get; set; }
    }

    public partial class QMS_T001_A
    {
        public int id { get; set; }
        public string doc_no { get; set; }
        public string ItemCode { get; set; }
        public string tr_code { get; set; }
        public string uncertainty { get; set; }
        public string unit_code { get; set; }
        public bool? active { get; set; }
        public string t_status { get; set; }
        public string add_by { get; set; }
        public DateTime add_date { get; set; }
        public string editby { get; set; }
        public DateTime? edit_date { get; set; }
        public string location_Id { get; set; }
        public string comp_code { get; set; }
        public string client { get; set; }
        public string lang_key { get; set; }
        public string user_source1 { get; set; }
        public string user_source2 { get; set; }
        // Scalar
        public string ItemName { get; set; }
        public string range { get; set; }
        public decimal? resolution { get; set; }
        public decimal? accuracy_up { get; set; }
        public string tr_name { get; set; }
        public DateTime? due_date { get; set; }
        public string inst_make { get; set; }
        public string model_no { get; set; }
        public string inst_srno { get; set; }
        public string cal_src { get; set; }
        public decimal? accuracy_down { get; set; }
        public decimal? least_count { get; set; }
        public decimal? upper_range { get; set; }
        public decimal? lower_range { get; set; }
    }

    public partial class QMS_T001_B
    {
        public int tm_id { get; set; }
        public string doc_no { get; set; }
        public string test_type_code { get; set; }
        public int? seq_no { get; set; }
        public int? value_id1 { get; set; }
        public int? value_id2 { get; set; }
        public int? value_id3 { get; set; }
        public int? value_id4 { get; set; }
        public int? value_id5 { get; set; }
        public int? value_id6 { get; set; }
        public int? value_id7 { get; set; }
        public int? value_id8 { get; set; }
        public int? value_id9 { get; set; }
        public int? value_id10 { get; set; }
        public decimal? value1 { get; set; }
        public decimal? value2 { get; set; }
        public decimal? value3 { get; set; }
        public decimal? value4 { get; set; }
        public decimal? value5 { get; set; }
        public decimal? value6 { get; set; }
        public decimal? value7 { get; set; }
        public decimal? value8 { get; set; }
        public decimal? value9 { get; set; }
        public decimal? value10 { get; set; }
        public decimal? value11 { get; set; }
        public decimal? value12 { get; set; }
        public decimal? value13 { get; set; }
        public decimal? value14 { get; set; }
        public decimal? value15 { get; set; }
        public decimal? value16 { get; set; }
        public decimal? value17 { get; set; }
        public decimal? value18 { get; set; }
        public decimal? value19 { get; set; }
        public decimal? value20 { get; set; }
        public decimal? value21 { get; set; }
        public decimal? value22 { get; set; }
        public decimal? value23 { get; set; }
        public decimal? value24 { get; set; }
        public decimal? value25 { get; set; }
        public decimal? value26 { get; set; }
        public decimal? value27 { get; set; }
        public decimal? value28 { get; set; }
        public decimal? value29 { get; set; }
        public decimal? value30 { get; set; }
        public decimal? value31 { get; set; }
        public decimal? value32 { get; set; }
        public decimal? value33 { get; set; }
        public decimal? value34 { get; set; }
        public decimal? value35 { get; set; }
        public decimal? value36 { get; set; }
        public decimal? value37 { get; set; }
        public decimal? value38 { get; set; }
        public decimal? value39 { get; set; }
        public decimal? value40 { get; set; }
        public decimal? value41 { get; set; }
        public decimal? value42 { get; set; }
        public decimal? value43 { get; set; }
        public decimal? value44 { get; set; }
        public decimal? value45 { get; set; }
        public decimal? value46 { get; set; }
        public decimal? value47 { get; set; }
        public decimal? value48 { get; set; }
        public decimal? value49 { get; set; }
        public decimal? value50 { get; set; }
        public decimal? value51 { get; set; }
        public decimal? value52 { get; set; }
        public decimal? value53 { get; set; }
        public decimal? value54 { get; set; }
        public decimal? value55 { get; set; }
        public decimal? value56 { get; set; }
        public decimal? value57 { get; set; }
        public decimal? value58 { get; set; }
        public decimal? value59 { get; set; }
        public decimal? value60 { get; set; }
        public decimal? u_value1 { get; set; }
        public decimal? u_value2 { get; set; }
        public decimal? u_value3 { get; set; }
        public decimal? u_value4 { get; set; }
        public decimal? u_value5 { get; set; }
        public decimal? u_value6 { get; set; }
        public decimal? u_value7 { get; set; }
        public decimal? u_value8 { get; set; }
        public decimal? u_value9 { get; set; }
        public decimal? u_value10 { get; set; }
        public decimal? u_value11 { get; set; }
        public decimal? u_value12 { get; set; }
        public decimal? u_value13 { get; set; }
        public decimal? u_value14 { get; set; }
        public decimal? u_value15 { get; set; }
        public decimal? u_value16 { get; set; }
        public decimal? u_value17 { get; set; }
        public decimal? u_value18 { get; set; }
        public decimal? u_value19 { get; set; }
        public decimal? u_value20 { get; set; }
        public decimal? u_value21 { get; set; }
        public decimal? u_value22 { get; set; }
        public decimal? u_value23 { get; set; }
        public decimal? u_value24 { get; set; }
        public decimal? u_value25 { get; set; }
        public decimal? u_value26 { get; set; }
        public decimal? u_value27 { get; set; }
        public decimal? u_value28 { get; set; }
        public decimal? u_value29 { get; set; }
        public decimal? u_value30 { get; set; }
        public string unit_code { get; set; }
        public string master_inst { get; set; }
        public bool? active { get; set; }
        public string t_status { get; set; }
        public string add_by { get; set; }
        public DateTime add_date { get; set; }
        public string editby { get; set; }
        public DateTime? edit_date { get; set; }
        public string location_Id { get; set; }
        public string comp_code { get; set; }
        public string client { get; set; }
        public string lang_key { get; set; }
        public string user_source1 { get; set; }
        public string user_source2 { get; set; }
        public decimal? value61 { get; set; }
        public decimal? value62 { get; set; }
        public decimal? dev_value { get; set; }
        public decimal? dev_mean_value { get; set; }
        public decimal? dev_per_value { get; set; }
        public int? degree_of_frdm { get; set; }
        public string remark { get; set; }
        public string column_value1 { get; set; }
        public string column_value2 { get; set; }
        public string column_value3 { get; set; }
        public string column_value4 { get; set; }
        public string column_value5 { get; set; }
        public string column_value6 { get; set; }
        public string column_value7 { get; set; }
        public string column_value8 { get; set; }
        public string column_value9 { get; set; }
        public string column_value10 { get; set; }
        public decimal? value63 { get; set; }
        public decimal? value64 { get; set; }
        public decimal? value65 { get; set; }
        public decimal? value66 { get; set; }
        public decimal? value67 { get; set; }
        public decimal? value68 { get; set; }
        public decimal? value69 { get; set; }
        public decimal? value70 { get; set; }
        public decimal? m_uncertainty { get; set; }
        public decimal? m_accuracy { get; set; }
        public decimal? m_resolution { get; set; }
        public decimal? coverage_factor { get; set; }
        public string conf_level { get; set; }
        public bool select31 { get; set; }
        public bool select32 { get; set; }
        public bool select33 { get; set; }
        public bool select34 { get; set; }
        public bool select35 { get; set; }
        public bool select36 { get; set; }
        public bool select37 { get; set; }
        public bool select38 { get; set; }
        public bool select39 { get; set; }
        public bool select40 { get; set; }
        public bool select41 { get; set; }
        public bool select42 { get; set; }
        public bool select43 { get; set; }
        public bool select44 { get; set; }
        public bool select45 { get; set; }
        public bool select46 { get; set; }
        public bool select47 { get; set; }
        public bool select48 { get; set; }
        public bool select49 { get; set; }
        public bool select50 { get; set; }
        public decimal? sensitivity_coeff { get; set; }
        public decimal? combine_uncertainty { get; set; }
        public decimal? eff_degree_of_frdm { get; set; }
        public decimal? expanded_uncertainty { get; set; }
        public decimal? expanded_uncertainty_per { get; set; }

        //Scalar
        public string hdr_name { get; set; }
        public string test_type_name { get; set; }
        public string master_inst_name { get; set; }
        public byte[] image1 { get; set; }
        public byte[] image2 { get; set; }
        public byte[] image3 { get; set; }
        public int deletion_id { get; set; }
    }

    public partial class QMS_T001_C
    {
        public int id { get; set; }
        public string doc_no { get; set; }
        public string test_type_code { get; set; }
        public decimal? value1 { get; set; }
        public decimal? value2 { get; set; }
        public decimal? value3 { get; set; }
        public decimal? value4 { get; set; }
        public decimal? value5 { get; set; }
        public decimal? value6 { get; set; }
        public decimal? value7 { get; set; }
        public decimal? value8 { get; set; }
        public decimal? value9 { get; set; }
        public decimal? value10 { get; set; }
        public decimal? value11 { get; set; }
        public decimal? value12 { get; set; }
        public decimal? value13 { get; set; }
        public decimal? value14 { get; set; }
        public decimal? value15 { get; set; }
        public decimal? value16 { get; set; }
        public decimal? value17 { get; set; }
        public decimal? value18 { get; set; }
        public decimal? value19 { get; set; }
        public decimal? value20 { get; set; }
        public decimal? u_value1 { get; set; }
        public decimal? u_value2 { get; set; }
        public decimal? u_value3 { get; set; }
        public decimal? u_value4 { get; set; }
        public decimal? u_value5 { get; set; }
        public decimal? u_value6 { get; set; }
        public decimal? u_value7 { get; set; }
        public decimal? u_value8 { get; set; }
        public decimal? u_value9 { get; set; }
        public decimal? u_value10 { get; set; }
        public decimal? l_value { get; set; }
        public decimal? h_value { get; set; }
        public decimal? std_value { get; set; }
        public decimal? value61 { get; set; }
        public decimal? value62 { get; set; }
        public string unit_code { get; set; }
        public string error_code { get; set; }
        public string u_remark1 { get; set; }
        public string u_remark2 { get; set; }
        public string u_remark3 { get; set; }
        public string master_inst { get; set; }
        public Nullable<bool> active { get; set; }
        public string t_status { get; set; }
        public string add_by { get; set; }
        public System.DateTime add_date { get; set; }
        public string editby { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string location_Id { get; set; }
        public string comp_code { get; set; }
        public string client { get; set; }
        public string lang_key { get; set; }
        public string user_source1 { get; set; }
        public string user_source2 { get; set; }
    }

    public partial class QMS_T001_D
    {
        public int id { get; set; }
        public string doc_no { get; set; }
        public string para_code { get; set; }
        public string value_code { get; set; }
        public bool? active { get; set; }
        public string para_name { get; set; }
        public string para_value { get; set; }
    }

    // Report Entity
    public class RptTestType
    {
        public int tm_id { get; set; }
        public string doc_no { get; set; }
        public string test_type_code { get; set; }
        public int? seq_no { get; set; }
        public int? value_id1 { get; set; }
        public int? value_id2 { get; set; }
        public int? value_id3 { get; set; }
        public int? value_id4 { get; set; }
        public int? value_id5 { get; set; }
        public int? value_id6 { get; set; }
        public int? value_id7 { get; set; }
        public int? value_id8 { get; set; }
        public int? value_id9 { get; set; }
        public int? value_id10 { get; set; }
        public decimal? value1 { get; set; }
        public decimal? value2 { get; set; }
        public decimal? value3 { get; set; }
        public decimal? value4 { get; set; }
        public decimal? value5 { get; set; }
        public decimal? value6 { get; set; }
        public decimal? value7 { get; set; }
        public decimal? value8 { get; set; }
        public decimal? value9 { get; set; }
        public decimal? value10 { get; set; }
        public decimal? value11 { get; set; }
        public decimal? value12 { get; set; }
        public decimal? value13 { get; set; }
        public decimal? value14 { get; set; }
        public decimal? value15 { get; set; }
        public decimal? value16 { get; set; }
        public decimal? value17 { get; set; }
        public decimal? value18 { get; set; }
        public decimal? value19 { get; set; }
        public decimal? value20 { get; set; }
        public decimal? value21 { get; set; }
        public decimal? value22 { get; set; }
        public decimal? value23 { get; set; }
        public decimal? value24 { get; set; }
        public decimal? value25 { get; set; }
        public decimal? value26 { get; set; }
        public decimal? value27 { get; set; }
        public decimal? value28 { get; set; }
        public decimal? value29 { get; set; }
        public decimal? value30 { get; set; }
        public decimal? value31 { get; set; }
        public decimal? value32 { get; set; }
        public decimal? value33 { get; set; }
        public decimal? value34 { get; set; }
        public decimal? value35 { get; set; }
        public decimal? value36 { get; set; }
        public decimal? value37 { get; set; }
        public decimal? value38 { get; set; }
        public decimal? value39 { get; set; }
        public decimal? value40 { get; set; }
        public decimal? value41 { get; set; }
        public decimal? value42 { get; set; }
        public decimal? value43 { get; set; }
        public decimal? value44 { get; set; }
        public decimal? value45 { get; set; }
        public decimal? value46 { get; set; }
        public decimal? value47 { get; set; }
        public decimal? value48 { get; set; }
        public decimal? value49 { get; set; }
        public decimal? value50 { get; set; }
        public decimal? value51 { get; set; }
        public decimal? value52 { get; set; }
        public decimal? value53 { get; set; }
        public decimal? value54 { get; set; }
        public decimal? value55 { get; set; }
        public decimal? value56 { get; set; }
        public decimal? value57 { get; set; }
        public decimal? value58 { get; set; }
        public decimal? value59 { get; set; }
        public decimal? value60 { get; set; }
        public decimal? value61 { get; set; }
        public decimal? value62 { get; set; }
        public decimal? u_value1 { get; set; }
        public decimal? u_value2 { get; set; }
        public decimal? u_value3 { get; set; }
        public decimal? u_value4 { get; set; }
        public decimal? u_value5 { get; set; }
        public decimal? u_value6 { get; set; }
        public decimal? u_value7 { get; set; }
        public decimal? u_value8 { get; set; }
        public decimal? u_value9 { get; set; }
        public decimal? u_value10 { get; set; }
        public decimal? u_value11 { get; set; }
        public decimal? u_value12 { get; set; }
        public decimal? u_value13 { get; set; }
        public decimal? u_value14 { get; set; }
        public decimal? u_value15 { get; set; }
        public decimal? u_value16 { get; set; }
        public decimal? u_value17 { get; set; }
        public decimal? u_value18 { get; set; }
        public decimal? u_value19 { get; set; }
        public decimal? u_value20 { get; set; }
        public decimal? u_value21 { get; set; }
        public decimal? u_value22 { get; set; }
        public decimal? u_value23 { get; set; }
        public decimal? u_value24 { get; set; }
        public decimal? u_value25 { get; set; }
        public decimal? u_value26 { get; set; }
        public decimal? u_value27 { get; set; }
        public decimal? u_value28 { get; set; }
        public decimal? u_value29 { get; set; }
        public decimal? u_value30 { get; set; }
        public string unit_code { get; set; }
        public string master_inst { get; set; }
        public bool? active { get; set; }
        public string t_status { get; set; }
        public string add_by { get; set; }
        public DateTime add_date { get; set; }
        public string editby { get; set; }
        public DateTime? edit_date { get; set; }
        public string location_Id { get; set; }
        public string comp_code { get; set; }
        public string client { get; set; }
        public string lang_key { get; set; }
        public string user_source1 { get; set; }
        public string user_source2 { get; set; }
        public decimal? dev_value { get; set; }
        public decimal? dev_mean_value { get; set; }
        public decimal? dev_per_value { get; set; }
        public int? degree_of_frdm { get; set; }
        public string remark { get; set; }
        public string column_value1 { get; set; }
        public string column_value2 { get; set; }
        public string column_value3 { get; set; }
        public string column_value4 { get; set; }
        public string column_value5 { get; set; }
        public string column_value6 { get; set; }
        public string column_value7 { get; set; }
        public string column_value8 { get; set; }
        public string column_value9 { get; set; }
        public string column_value10 { get; set; }
        public decimal? value63 { get; set; }
        public decimal? value64 { get; set; }
        public decimal? value65 { get; set; }
        public decimal? value66 { get; set; }
        public decimal? value67 { get; set; }
        public decimal? value68 { get; set; }
        public decimal? value69 { get; set; }
        public decimal? value70 { get; set; }
        public decimal? m_uncertainty { get; set; }
        public decimal? m_accuracy { get; set; }
        public decimal? m_resolution { get; set; }
        public decimal? coverage_factor { get; set; }
        public string conf_level { get; set; }
        public bool select31 { get; set; }
        public bool select32 { get; set; }
        public bool select33 { get; set; }
        public bool select34 { get; set; }
        public bool select35 { get; set; }
        public bool select36 { get; set; }
        public bool select37 { get; set; }
        public bool select38 { get; set; }
        public bool select39 { get; set; }
        public bool select40 { get; set; }
        public bool select41 { get; set; }
        public bool select42 { get; set; }
        public bool select43 { get; set; }
        public bool select44 { get; set; }
        public bool select45 { get; set; }
        public bool select46 { get; set; }
        public bool select47 { get; set; }
        public bool select48 { get; set; }
        public bool select49 { get; set; }
        public bool select50 { get; set; }
        public decimal? sensitivity_coeff { get; set; }
        public decimal? combine_uncertainty { get; set; }
        public decimal? eff_degree_of_frdm { get; set; }
        public decimal? expanded_uncertainty { get; set; }
        public decimal? expanded_uncertainty_per { get; set; }
        //Scalar
        public string test_type_name { get; set; }
        public string formula_code { get; set; }
    }
    public partial class QMS_T001_E
    {
        public int id { get; set; }
        public string doc_no { get; set; }
        public string tl_code { get; set; }
        public bool? task_done { get; set; }
        public string remark { get; set; }
        public bool? active { get; set; }
        // Scalar
        public string short_text { get; set; }
    }
    public partial class QMS_T001_F
    {
        public int id { get; set; }
        public string doc_no { get; set; }
        public string test_type_code { get; set; }
        public string env_code { get; set; }
        public string env_name { get; set; }
        public decimal? std_value { get; set; }
        public decimal? upper_value { get; set; }
        public decimal? lower_value { get; set; }
        public decimal? r_std_value { get; set; }
        public string std_value_unit { get; set; }
        public decimal? resolution { get; set; }
        public string resolution_unit { get; set; }
        public decimal? variation { get; set; }
        public decimal? variation_per { get; set; }
        public bool? active { get; set; }
        public string t_status { get; set; }
        public string add_by { get; set; }
        public DateTime add_date { get; set; }
        public string editby { get; set; }
        public DateTime? edit_date { get; set; }
        public string location_Id { get; set; }
        public string comp_code { get; set; }
        public string client { get; set; }
        public string lang_key { get; set; }
        public string user_source1 { get; set; }
        public string user_source2 { get; set; }
    }
    public partial class RptMISInspection
    {
        public string doc_no { get; set; }
        public string doc_cat { get; set; }
        public string doc_type { get; set; }
        public string lab_code { get; set; }
        public string barcode { get; set; }
        public string test_code { get; set; }
        public string ref_doc_no { get; set; }
        public string rig_code { get; set; }
        public string tr_code { get; set; }
        public string temperature { get; set; }
        public string humidity { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public string master_inst { get; set; }
        public string EmpId { get; set; }
        public string cal_type { get; set; }
        public string po_no { get; set; }
        public string PartyId { get; set; }
        public int ContInfoId { get; set; }
        public DateTime? cal_date { get; set; }
        public DateTime? last_date { get; set; }
        public int cal_freq { get; set; }
        public string cal_period { get; set; }
        public DateTime? next_date { get; set; }
        public string u_remark1 { get; set; }
        public string u_remark2 { get; set; }
        public string u_remark3 { get; set; }
        public bool? active { get; set; }
        public string t_status { get; set; }
        public string add_by { get; set; }
        public DateTime add_date { get; set; }
        public string editby { get; set; }
        public DateTime? edit_date { get; set; }
        public string location_Id { get; set; }
        public string comp_code { get; set; }
        public string client { get; set; }
        public string lang_key { get; set; }
        public string user_source1 { get; set; }
        public string user_source2 { get; set; }
        public string start_temp { get; set; }
        public string end_temp { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
        public DateTime? doc_date { get; set; }
        public DateTime? due_date { get; set; }
        public string PartyNm { get; set; }
        public string inst_code { get; set; }
        public string inst_name { get; set; }
        public string serv_type { get; set; }
        public string insp_lot_no { get; set; }
        public string resolution { get; set; }
        public string middle_temp { get; set; }
        public string inst_type { get; set; }
        //Scalar
        public string test_name { get; set; }
        public string inst_id { get; set; }
        public string inst_make { get; set; }
        public string inst_srno { get; set; }
        public string model_no { get; set; }
        public string least_count { get; set; }
        public string range { get; set; }
        public string accuracy { get; set; }
        public string cont_per_name { get; set; }
        public string EmpNm { get; set; }
        public string tr_name { get; set; }
        public string rig_name { get; set; }
        public string lab_name { get; set; }
        public string to_mail_id { get; set; }
        public string inst_cond { get; set; }
        public string approvernm { get; set; }
    }
    public partial class QMS_T001_B_UNC
    {
        public int tm_id { get; set; }
        public string doc_no { get; set; }
        public string test_type_code { get; set; }
        public int? seq_no { get; set; }
        public int? value_id1 { get; set; }
        public int? value_id2 { get; set; }
        public int? value_id3 { get; set; }
        public int? value_id4 { get; set; }
        public int? value_id5 { get; set; }
        public int? value_id6 { get; set; }
        public int? value_id7 { get; set; }
        public int? value_id8 { get; set; }
        public int? value_id9 { get; set; }
        public int? value_id10 { get; set; }
        public decimal? value1 { get; set; }
        public decimal? value2 { get; set; }
        public decimal? value3 { get; set; }
        public decimal? value4 { get; set; }
        public decimal? value5 { get; set; }
        public decimal? value6 { get; set; }
        public decimal? value7 { get; set; }
        public decimal? value8 { get; set; }
        public decimal? value9 { get; set; }
        public decimal? value10 { get; set; }
        public decimal? value11 { get; set; }
        public decimal? value12 { get; set; }
        public decimal? value13 { get; set; }
        public decimal? value14 { get; set; }
        public decimal? value15 { get; set; }
        public decimal? value16 { get; set; }
        public decimal? value17 { get; set; }
        public decimal? value18 { get; set; }
        public decimal? value19 { get; set; }
        public decimal? value20 { get; set; }
        public decimal? value21 { get; set; }
        public decimal? value22 { get; set; }
        public decimal? value23 { get; set; }
        public decimal? value24 { get; set; }
        public decimal? value25 { get; set; }
        public decimal? value26 { get; set; }
        public decimal? value27 { get; set; }
        public decimal? value28 { get; set; }
        public decimal? value29 { get; set; }
        public decimal? value30 { get; set; }
        public decimal? value31 { get; set; }
        public decimal? value32 { get; set; }
        public decimal? value33 { get; set; }
        public decimal? value34 { get; set; }
        public decimal? value35 { get; set; }
        public decimal? value36 { get; set; }
        public decimal? value37 { get; set; }
        public decimal? value38 { get; set; }
        public decimal? value39 { get; set; }
        public decimal? value40 { get; set; }
        public decimal? value41 { get; set; }
        public decimal? value42 { get; set; }
        public decimal? value43 { get; set; }
        public decimal? value44 { get; set; }
        public decimal? value45 { get; set; }
        public decimal? value46 { get; set; }
        public decimal? value47 { get; set; }
        public decimal? value48 { get; set; }
        public decimal? value49 { get; set; }
        public decimal? value50 { get; set; }
        public decimal? value51 { get; set; }
        public decimal? value52 { get; set; }
        public decimal? value53 { get; set; }
        public decimal? value54 { get; set; }
        public decimal? value55 { get; set; }
        public decimal? value56 { get; set; }
        public decimal? value57 { get; set; }
        public decimal? value58 { get; set; }
        public decimal? value59 { get; set; }
        public decimal? value60 { get; set; }
        public decimal? u_value1 { get; set; }
        public decimal? u_value2 { get; set; }
        public decimal? u_value3 { get; set; }
        public decimal? u_value4 { get; set; }
        public decimal? u_value5 { get; set; }
        public decimal? u_value6 { get; set; }
        public decimal? u_value7 { get; set; }
        public decimal? u_value8 { get; set; }
        public decimal? u_value9 { get; set; }
        public decimal? u_value10 { get; set; }
        public decimal? u_value11 { get; set; }
        public decimal? u_value12 { get; set; }
        public decimal? u_value13 { get; set; }
        public decimal? u_value14 { get; set; }
        public decimal? u_value15 { get; set; }
        public decimal? u_value16 { get; set; }
        public decimal? u_value17 { get; set; }
        public decimal? u_value18 { get; set; }
        public decimal? u_value19 { get; set; }
        public decimal? u_value20 { get; set; }
        public decimal? u_value21 { get; set; }
        public decimal? u_value22 { get; set; }
        public decimal? u_value23 { get; set; }
        public decimal? u_value24 { get; set; }
        public decimal? u_value25 { get; set; }
        public decimal? u_value26 { get; set; }
        public decimal? u_value27 { get; set; }
        public decimal? u_value28 { get; set; }
        public decimal? u_value29 { get; set; }
        public decimal? u_value30 { get; set; }
        public string unit_code { get; set; }
        public string master_inst { get; set; }
        public bool? active { get; set; }
        public string t_status { get; set; }
        public string add_by { get; set; }
        public DateTime add_date { get; set; }
        public string editby { get; set; }
        public DateTime? edit_date { get; set; }
        public string location_Id { get; set; }
        public string comp_code { get; set; }
        public string client { get; set; }
        public string lang_key { get; set; }
        public string user_source1 { get; set; }
        public string user_source2 { get; set; }
        public decimal? value61 { get; set; }
        public decimal? value62 { get; set; }
        public decimal? dev_value { get; set; }
        public decimal? dev_mean_value { get; set; }
        public decimal? dev_per_value { get; set; }
        public int? degree_of_frdm { get; set; }
        public string remark { get; set; }
        public string column_value1 { get; set; }
        public string column_value2 { get; set; }
        public string column_value3 { get; set; }
        public string column_value4 { get; set; }
        public string column_value5 { get; set; }
        public string column_value6 { get; set; }
        public string column_value7 { get; set; }
        public string column_value8 { get; set; }
        public string column_value9 { get; set; }
        public string column_value10 { get; set; }
        public decimal? value63 { get; set; }
        public decimal? value64 { get; set; }
        public decimal? value65 { get; set; }
        public decimal? value66 { get; set; }
        public decimal? value67 { get; set; }
        public decimal? value68 { get; set; }
        public decimal? value69 { get; set; }
        public decimal? value70 { get; set; }
        public decimal? m_uncertainty { get; set; }
        public decimal? m_accuracy { get; set; }
        public decimal? m_resolution { get; set; }
        public decimal? coverage_factor { get; set; }
        public string conf_level { get; set; }
        public bool select31 { get; set; }
        public bool select32 { get; set; }
        public bool select33 { get; set; }
        public bool select34 { get; set; }
        public bool select35 { get; set; }
        public bool select36 { get; set; }
        public bool select37 { get; set; }
        public bool select38 { get; set; }
        public bool select39 { get; set; }
        public bool select40 { get; set; }
        public bool select41 { get; set; }
        public bool select42 { get; set; }
        public bool select43 { get; set; }
        public bool select44 { get; set; }
        public bool select45 { get; set; }
        public bool select46 { get; set; }
        public bool select47 { get; set; }
        public bool select48 { get; set; }
        public bool select49 { get; set; }
        public bool select50 { get; set; }
        public decimal? sensitivity_coeff { get; set; }
        public decimal? combine_uncertainty { get; set; }
        public decimal? eff_degree_of_frdm { get; set; }
        public decimal? expanded_uncertainty { get; set; }
        public decimal? expanded_uncertainty_per { get; set; }
        //Scalar
        public string master_inst_name { get; set; }
        public byte[] image1 { get; set; }
        public byte[] image2 { get; set; }
        public byte[] image3 { get; set; }
        public int deletion_id { get; set; }
    }

}
