using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Reflection.EF.CRM
{
    public class SEL_T001 : ObjectBase
    {
        public int id { get; set; }
        public string sono { get; set; }
        public string tr_mode { get; set; }
        public string tr_type { get; set; }
        public string tr_party { get; set; }
        public string tr_name { get; set; }
        public Nullable<System.DateTime> sodate { get; set; }
        public string order_to_plant { get; set; }
        public Nullable<int> bill_address_id { get; set; }
        public Nullable<int> del_address { get; set; }
        public string cust_ref { get; set; }
        public Nullable<System.DateTime> cust_ref_date { get; set; }
        public Nullable<System.DateTime> valid_from_date { get; set; }
        public string quotation_no { get; set; }
        public Nullable<System.DateTime> quotation_submt_dt { get; set; }
        public string buyer_name { get; set; }
        public Nullable<System.DateTime> expect_date { get; set; }
        public Nullable<int> buyer { get; set; }
        public string EmpId { get; set; }
        public string address { get; set; }
        public string address1 { get; set; }
        public string country_nm { get; set; }
        public string state_nm { get; set; }
        public string city { get; set; }
        public string pincode { get; set; }
        public string phone_no { get; set; }
        public string mobile_no { get; set; }
        public string phone_ext { get; set; }
        public string mail_id { get; set; }
        public string web_site { get; set; }
        public string p_term_code { get; set; }
        public string notes { get; set; }
        public Nullable<bool> delivered { get; set; }
        public Nullable<bool> invoice { get; set; }
        public Nullable<decimal> tax_amt { get; set; }
        public Nullable<decimal> untax_amt { get; set; }
        public Nullable<decimal> total_amt { get; set; }
        public string amt_inword { get; set; }
        public bool active { get; set; }
        public System.DateTime add_date { get; set; }
        public string add_by { get; set; }
        public DateTime? edit_date { get; set; }
        public string editby { get; set; }
        public string doc_type { get; set; }
        public string doc_cat { get; set; }
        public string ref_doc_no { get; set; }
        public string ref_doc_type { get; set; }
        public Nullable<System.DateTime> valid_to_date { get; set; }
        public string so_code { get; set; }
        public string div_code { get; set; }
        public string sales_person_cd { get; set; }
        public string j_code { get; set; }
        public string PartyId { get; set; }
        public string party_name { get; set; }
        public string fin_year { get; set; }
        public string posting_period { get; set; }
        public string store_code { get; set; }
        public string cust_cat_no { get; set; }
        public string curr_code { get; set; }
        public string wa_code { get; set; }
        public Nullable<System.DateTime> date_approve { get; set; }
        public string reference { get; set; }
        public string invoice_method { get; set; }
        public Nullable<bool> shipped { get; set; }
        public Nullable<System.DateTime> shipped_date { get; set; }
        public Nullable<System.DateTime> min_planned_date { get; set; }
        public string dc_code { get; set; }
        public string sg_code { get; set; }
        public string sales_office { get; set; }
        public string business_area { get; set; }
        public string cost_center { get; set; }
        public string po_no { get; set; }
        public string po_type { get; set; }
        public Nullable<System.DateTime> po_date { get; set; }
        public string version { get; set; }
        public string location_Id { get; set; }
        public string comp_code { get; set; }
        public string ship_to_party { get; set; }
        public string t_status { get; set; }
        public string para1 { get; set; }
        public string para2 { get; set; }
        public string para3 { get; set; }
        public string pre_carrage { get; set; }
        public string pre_carrage_place { get; set; }
        public string country_code { get; set; }
        public string port_load { get; set; }
        public string port_desc { get; set; }
        public string port_final { get; set; }
        public string final_dest { get; set; }
        public string ship_terms { get; set; }
        public string cf_agent_cd { get; set; }
        public string lic_cod { get; set; }
        public string adv_lic_cd { get; set; }
        public string org_country_cd { get; set; }
        public string pack_rem { get; set; }
        public string ship_mark { get; set; }
        public string ship_mode { get; set; }
        public string bank_code { get; set; }
        public string nastro_bank_cd { get; set; }
        public string ship_cond { get; set; }
        public string del_plant { get; set; }
        public string local_export { get; set; }
        public string ind_trade { get; set; }
        public string transporter_cd { get; set; }
        public Nullable<decimal> gross_wt { get; set; }
        public Nullable<decimal> net_wt { get; set; }
        public string unit_code { get; set; }
        public string volume_unit { get; set; }
        public Nullable<decimal> qty_tol { get; set; }
        public Nullable<decimal> amt_tol { get; set; }
        public string ref_version { get; set; }
        public Nullable<decimal> volume { get; set; }
        public string incoterms { get; set; }
        public Nullable<System.DateTime> app_closing_dt { get; set; }
        public Nullable<System.DateTime> quotation_deadline { get; set; }
        public string bid_inv_no { get; set; }
        public Nullable<decimal> short_excess_amt { get; set; }
        public string short_excess_flag { get; set; }
        public string gr_ind { get; set; }
        public string invoice_ind { get; set; }
        public string gr_inv_ind { get; set; }
        public string order_ack_ind { get; set; }
        public string order_ack_no { get; set; }
        public string pur_agree_no { get; set; }
        public string pur_agree_item_cd { get; set; }
        public string cust_mat_no { get; set; }
        public Nullable<decimal> abs_deviation_qty { get; set; }
        public Nullable<decimal> per_deviation_qty { get; set; }
        public Nullable<decimal> over_del_tol { get; set; }
        public Nullable<decimal> under_del_tol { get; set; }
        public string vendor_bank_code { get; set; }
        public string revision_no { get; set; }
        public string revision_ind { get; set; }
        public string rev_ref_no { get; set; }
        public string down_ind { get; set; }
        public Nullable<decimal> down_per { get; set; }
        public Nullable<decimal> down_pay { get; set; }
        public Nullable<System.DateTime> down_date { get; set; }
        public string refferencing_party { get; set; }
        public string hb_acc { get; set; }
        public string swift_code { get; set; }
        public string ifsc_code { get; set; }
        public string terms_cond { get; set; }
        public Nullable<decimal> round_up { get; set; }
        public string gl_code { get; set; }
        public string notify_party { get; set; }
        public string notify_party2 { get; set; }
        public string referring_party { get; set; }
        public string catalogue_code { get; set; }
        public Nullable<decimal> ex_rate { get; set; }
        public Nullable<System.DateTime> order_ack_date { get; set; }
        public Nullable<bool> acknowledged { get; set; }
        public Nullable<bool> abg_flag { get; set; }
        public Nullable<int> abg_days { get; set; }
        public Nullable<System.DateTime> abg_release_date { get; set; }
        public string release_mode { get; set; }
        public Nullable<decimal> roundup_total { get; set; }
        public Nullable<System.DateTime> ref_doc_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string validator { get; set; }
        public string delivery_ind { get; set; }
        public string seller_name { get; set; }
        public string ship_to_party_name { get; set; }
        public string notify_party_name { get; set; }
        public string notify_party_name2 { get; set; }
        public string bank_name { get; set; }
        public string nastro_bank_name { get; set; }
        public string cf_agent_name { get; set; }
        public string transporter_name { get; set; }
        public string referring_party_name { get; set; }
        public string sales_org { get; set; }
        public string sg_name { get; set; }
        public string cost_center_Desc { get; set; }
        public string inco_desc { get; set; }
        public string doc_type_doc_no { get; set; }
        public string doc_type_user { get; set; }
        public string doc_desc { get; set; }
        public string delivery_address { get; set; }
        public string billing_address { get; set; }
        public string payment_term { get; set; }
        public string shipping_mark { get; set; }
        public string insurance { get; set; }
        public string packing { get; set; }
        public string transhipment { get; set; }
        public string partshipment { get; set; }
        public Nullable<System.DateTime> shipment_date { get; set; }
        public Nullable<System.DateTime> validity_date { get; set; }
        public string payment_mode { get; set; }
        public string ship_to_address { get; set; }
        public string sold_to_address { get; set; }
        public string address1_s { get; set; }
        public string address2_s { get; set; }
        public string country_nm_s { get; set; }
        public string state_nm_s { get; set; }
        public string city_s { get; set; }
        public string pincode_s { get; set; }
        public Nullable<bool> qty_percent { get; set; }
        public Nullable<bool> amt_percent { get; set; }
        public string EmpMobNo { get; set; }
        public string EmpPhNo { get; set; }
        public string EmpEmailId { get; set; }
        public string PersnEmailId { get; set; }
        public string PersnMobNo { get; set; }
        public string PersnPhNo { get; set; }
        public string ifsccode { get; set; }
        public string acc_number { get; set; }
        public string branch { get; set; }
        public string user_source11 { get; set; }
        public string status_remark { get; set; }
        public string p_term { get; set; }
        public string dcat_name { get; set; }
        public byte[] authorised_signature { get; set; }
        public string LoctnNm { get; set; }
        public string PartyEmailId { get; set; }
        public string PersonEmailId { get; set; }
        public Nullable<int> ref_party_contact { get; set; }
        public string ref_contact_name { get; set; }
        public string language { get; set; }
        public string doc_history_no { get; set; }
        public string CSTNo { get; set; }
        public string VATNo { get; set; }
        public string service_tax_no { get; set; }
        public string PanNo { get; set; }
        public string TranParty_name { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public string remark4 { get; set; }
        public string notify_nm { get; set; }
        public string notify_ph { get; set; }
        public string notify_address { get; set; }
        public string bank_city { get; set; }
        public string bank_zip { get; set; }
        public string bank_country { get; set; }
        public string location { get; set; }
        public string incoterm2 { get; set; }
        public Nullable<decimal> order_limit { get; set; }
        public Nullable<bool> order_limit_tax { get; set; }
        public string symbol { get; set; }
        public Nullable<decimal> net_value { get; set; }
        public string withholding_tax { get; set; }
        public Nullable<decimal> withholding_value { get; set; }
        public Nullable<decimal> withholding_ex_amt { get; set; }
        public Nullable<decimal> local_tax_amt { get; set; }
        public Nullable<decimal> local_total_amt { get; set; }
        public Nullable<decimal> local_round_up { get; set; }
        public Nullable<decimal> local_roundup_total { get; set; }
        public Nullable<decimal> local_net_value { get; set; }
        public Nullable<decimal> other_charges { get; set; }
        public string bom_no { get; set; }
        public Nullable<decimal> gross_value { get; set; }
        public Nullable<decimal> effective_value { get; set; }
        public Nullable<decimal> disc_amt { get; set; }
        public Nullable<decimal> tax_amount { get; set; }

        public string gst_PartyId { get; set; }
        public string buss_place { get; set; }
        public string plc_name { get; set; }
        public string gstinno { get; set; }
        public Nullable<System.DateTime> gstindate { get; set; }

        public string soldto_buss_place { get; set; }
        public string shipto_buss_place { get; set; }
        public string FaxNo { get; set; }
        public string FaxNos { get; set; }
        public string PhNo { get; set; }
        public string PhNos { get; set; }
        public string crm_doc_no { get; set; }
        public string t_display { get; set; }
        public string ref_doc_cat { get; set; }
        public string notify2_address { get; set; }
        public string weight_unit { get; set; }
        public string account_no { get; set; }
        public string project_location { get; set; }
        public string title { get; set; }
        public string DesigName { get; set; }
        public string vendor_remark { get; set; }
        public string textdata { get; set; }
        public string micr_code { get; set; }
        public string acc_no { get; set; } // Bank Account Number
        public string acc_name { get; set; } // Bank Account Name
        public string ad_code { get; set; }
        public string acc_type { get; set; } // Bank Account Type Current or Saving
        public string iban_no { get; set; }
        public string letter_text { get; set; }
        public string body_text { get; set; }
        public string header_text { get; set; }
        public string footer_text { get; set; }
        public string project_id { get; set; }
        public string element_id { get; set; }
        public int? element_no { get; set; }
        public string date_type { get; set; }
        public string billing_type { get; set; }
        public string add_code_del { get; set; }
        public string add_code_bil { get; set; }
        public string cp_code { get; set; }

        public string billing_type_name { get; set; }
        public string date_type_name { get; set; }
        public string abg_bank { get; set; }
        public decimal? abg_value { get; set; }
        public string abg_type { get; set; }
        public string abg_no { get; set; }
        public DateTime? abg_start_date { get; set; }
        public string project_name { get; set; }
        public string element_name { get; set; }
        public string catlog_name { get; set; }
        public bool? ind_source { get; set; } // Not required in Web Project because it is only to check reference value to vlidate reference party if customer comes with rrefrence else it is consider as direct customer without reference of commision. If refence exist, user need to select reference party in partner function.

        #region Scalars for Filtering View

        public string fltr_location_Id { get; set; }
        public string fltr_t_status { get; set; }
        public string fltr_t_display { get; set; }
        public string fltr_SoldToPartyID { get; set; }
        public string fltr_SoldToPartyNM { get; set; }
        public string fltr_SalesPersonID { get; set; }
        public string fltr_SalesPersonNM { get; set; }
        public DateTime? Fltr_FrmDate { get; set; }
        public DateTime? Fltr_ToDate { get; set; }
        public bool Fltr_active { get; set; }
        public string Fltr_doc_type { get; set; }
        public string Fltr_PartyId { get; set; }
        public string Fltr_PartyNm { get; set; }
        public string Fltr_SalesPersonID { get; set; }
        public string Fltr_SalesPersonNM { get; set; }


        #endregion

        public string XmlDataDocument_SEL_T001_A { get; set; }
        public string XDOC_SEL_T001_PART { get; set; }
        public string XmlDataDocument_ACC_T006_B { get; set; }
        public string XmlDataDocument_SEL_T002 { get; set; }
        public string XmlDataDocument_SEL_T002_A { get; set; }
        public string XmlDataDocument_ACC_T006_D { get; set; }
        public string XmlDataDocument_FlipGrid { get; set; }
        public string XmlDataDocument_COM_T003 { get; set; }
        public string XmlDataDocument_SEL_T001_E { get; set; }
        public string XDOC_TC { get; set; }
        public string XDOC_RS { get; set; }

        //=================================================================================================================

    }
    public partial class SEL_T001_A
    {
        public int id { get; set; }
        public string sono { get; set; }
        public string order_to_plant { get; set; }
        public string ItemCode { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public int line_id { get; set; }
        public string unit_code { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public string tax_id { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public bool active { get; set; }
        public string location_Id { get; set; }
        public string comp_code { get; set; }
        public string PartyId { get; set; }
        public System.DateTime add_date { get; set; }
        public string add_by { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string editby { get; set; }
        public string req_no { get; set; }
        public string plan_b_id { get; set; }
        public string item_cat { get; set; }
        public string sku { get; set; }
        public string sku_desc { get; set; }
        public Nullable<System.DateTime> min_planned_date { get; set; }
        public string t_status { get; set; }
        public Nullable<decimal> conversn_fact { get; set; }
        public decimal? gross_wt { get; set; }
        public decimal? net_wt { get; set; }
        public string weight_unit_cd { get; set; }
        public decimal? volume { get; set; }
        public string volume_unit_cd { get; set; }
        public string move_dest_id { get; set; }
        public Nullable<bool> invoiced { get; set; }
        public Nullable<System.DateTime> date_planned { get; set; }
        public Nullable<int> account_analytic_id { get; set; }
        public string acc_code { get; set; }
        public string store_code { get; set; }
        public string wa_code { get; set; }
        public string para1 { get; set; }
        public string para2 { get; set; }
        public string para3 { get; set; }
        public Nullable<int> para4 { get; set; }
        public string para5 { get; set; }
        public string para6 { get; set; }
        public string para7 { get; set; }
        public Nullable<decimal> para8 { get; set; }
        public string para9 { get; set; }
        public string para10 { get; set; }
        public string para11 { get; set; }
        public Nullable<bool> para12 { get; set; }
        public Nullable<System.DateTime> para13 { get; set; }
        public string para14 { get; set; }
        public string para15 { get; set; }
        public string para16 { get; set; }
        public Nullable<decimal> para17 { get; set; }
        public string para18 { get; set; }
        public string para19 { get; set; }
        public string para20 { get; set; }
        public string para21 { get; set; }
        public string para22 { get; set; }
        public string para23 { get; set; }
        public Nullable<int> para24 { get; set; }
        public string supp_code { get; set; }
        public string para26 { get; set; }
        public string para27 { get; set; }
        public Nullable<int> para28 { get; set; }
        public string cust_ref { get; set; }
        public Nullable<System.DateTime> cust_ref_date { get; set; }
        public string bid_inv_no { get; set; }
        public string quotation_no { get; set; }
        public Nullable<decimal> short_excess_amt { get; set; }
        public string short_excess_flag { get; set; }
        public string delivery_ind { get; set; }
        public string gr_inv_ind { get; set; }
        public string order_ack_ind { get; set; }
        public string order_ack_no { get; set; }
        public string pur_agree_no { get; set; }
        public string pur_agree_item_cd { get; set; }
        public string ref_doc_no { get; set; }
        public Nullable<System.DateTime> ref_doc_date { get; set; }
        public string ref_doc_type { get; set; }
        public string cust_mat_no { get; set; }
        public Nullable<decimal> abs_deviation_qty { get; set; }
        public Nullable<decimal> per_deviation_qty { get; set; }
        public Nullable<decimal> over_del_tol { get; set; }
        public Nullable<decimal> under_del_tol { get; set; }
        public string gr_ind { get; set; }
        public string incoterms { get; set; }
        public string user_source1 { get; set; }
        public string user_source2 { get; set; }
        public string p_term_code { get; set; }
        public Nullable<int> pack_style { get; set; }
        public string terms_cond { get; set; }
        public string gl_code { get; set; }
        public string notify_party { get; set; }
        public string fin_year { get; set; }
        public string posting_period { get; set; }
        public string rel_delivery { get; set; }
        public string rel_billing { get; set; }
        public Nullable<int> ref_item_row_id { get; set; }
        public string status_remark { get; set; }
        public string CstmrItmCod { get; set; }
        public string textdata { get; set; }
        public string PartyNm { get; set; }
        public string sch_no { get; set; }
        public string sch_date { get; set; }
        public string ink { get; set; }
        public string ild { get; set; }
        public Nullable<decimal> shank_dia { get; set; }
        public Nullable<int> tot_len_id { get; set; }
        public string total_len { get; set; }
        public string ink1 { get; set; }
        public string ild1 { get; set; }
        public string PhNo { get; set; }
        public string FaxNo { get; set; }
        public string PhNos { get; set; }
        public string FaxNos { get; set; }
        public string ModelNo { get; set; }
        public string BallType { get; set; }
        public string WireType { get; set; }
        public Nullable<decimal> BallDia { get; set; }
        public Nullable<bool> StockUnt { get; set; }
        public string SubCatCode { get; set; }
        public int ref_item_line_id { get; set; }
        public string doc_history_no { get; set; }
        public Nullable<int> local_discount { get; set; }
        public Nullable<int> local_sub_total { get; set; }
        public Nullable<decimal> net_value { get; set; }
        public Nullable<decimal> local_net_value { get; set; }
        public string bom_no { get; set; }
        public Nullable<int> gross_value { get; set; }
        public Nullable<int> effective_value { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public string discount_type { get; set; }
        public Nullable<decimal> discount_amt { get; set; }
        public string article_no { get; set; }
        //Added by Priya
        public int pkgid { get; set; }
        public string pkgunit { get; set; }
        public string alert1 { get; set; }
        public string symbol { get; set; }
        public Nullable<decimal> bal_qty { get; set; }
        public string ship_to_Party { get; set; }
        public int? ship_to_add { get; set; }
        public string buss_place { get; set; }
        public string hs_code { get; set; }
        public string crm_doc_no { get; set; }
        public string t_display { get; set; }
        public string client { get; set; }
        public string price_qty_uom { get; set; }
        public decimal? price_qty { get; set; }
        public decimal? qty_price { get; set; }
        public bool? ind_sku { get; set; }
        public string element_id { get; set; }
        public int? element_no { get; set; }
        public string tl_code { get; set; }
        public int? tl_counter { get; set; }
        public int? bom_counter { get; set; }
        public string weight_unit { get; set; }
        public string volume_unit { get; set; }
        public string ProdNm { get; set; }
        public string ItemName { get; set; }
        public string item_category { get; set; }
        public string item_code_party { get; set; }
        public string item_name_party { get; set; }

    }
    public partial class SEL_T001_PART : ObjectBase
    {
        public int id { get; set; }
        public string comp_code { get; set; }
        public string doc_no { get; set; }
        public int? sd_item_row_id { get; set; }
        public string pf_code { get; set; }
        public string party_code { get; set; } // SD Party
        public string party_code2 { get; set; } // Supplier for this Sales Document or Item.
        public string emp_id { get; set; }
        public string emp_name { get; set; }
        public string contact_no { get; set; }
        public string email_id { get; set; }
        public string add_code { get; set; }
        public string short_text { get; set; }
        public string active { get; set; }

        //Scalar
        public string pf_name { get; set; }
        public string party_name { get; set; }
        public string party_name2 { get; set; }
        public string location { get; set; }

    }

    public partial class SEL_T001_C
    {
        public int id { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<int> sequence { get; set; }
        public string doc_no { get; set; }
        public string manual { get; set; }
        public Nullable<decimal> base_amount { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> @base { get; set; }
        public Nullable<int> tax_code_id { get; set; }
        public Nullable<int> account_analytic_id { get; set; }
        public Nullable<int> base_code_id { get; set; }
        public string tax_name { get; set; }
        public string gl_code { get; set; }
        public string ItemCode { get; set; }
        public string sku { get; set; }
        public Nullable<int> item_row_id { get; set; }
        public string fin_year { get; set; }
        public string posting_period { get; set; }
        public Nullable<bool> active { get; set; }
        public string location_Id { get; set; }
        public string comp_code { get; set; }
        public int item_line_id { get; set; }
        public string dc_ind { get; set; }
        public string curr_code { get; set; }
        public Nullable<decimal> exch_rate { get; set; }
        public string local_curr { get; set; }
        public Nullable<decimal> amt_local_curr { get; set; }
        public string fix_per { get; set; }
        public string symbol { get; set; }
        //Added by Priya
        public string con_type { get; set; }
        public string con_cat { get; set; }
        public int acc_seq { get; set; }
        public string trns_key_code { get; set; }
        public string acc_key1 { get; set; }
        public string record_no { get; set; }
        public decimal? price_uom { get; set; }
        public string doc_uom_con { get; set; }
        public decimal? no_base_uom { get; set; }
        public decimal? dno_base_uo { get; set; }
        public string ind_con_acc { get; set; }
        public string vendor_code { get; set; }
        public string customera_code { get; set; }      
        public decimal? rnd_diff { get; set; }
        public decimal? con_value { get; set; }
        public string ind_max_base { get; set; }       
        public string ind_max_amt { get; set; }
        public string withholding_tax { get; set; }
      
        //Added by Priya on 2/5/2017
        public int stepno { get; set; }
        public int scounter { get; set; }
        public string trns_scope { get; set; }
        public decimal? pricing_date { get; set; }
        public string calc_type { get; set; }
        public decimal? con_qty { get; set; }
        public string ind_stats { get; set; }
        public string scale_type { get; set; }
        public decimal? scale_qty { get; set; }
        public string ind_con_acr { get; set; }
        public string PartyId { get; set; }
        public string tax_code { get; set; }
        public string origin_ind { get; set; }
        public string con_control { get; set; }
        public string round_method { get; set; }
        public string grp_con { get; set; }
        public string is_qty { get; set; }
        public string con_record_no { get; set; }
        public int con_seq { get; set; }
        public string con_class { get; set; }
        public int cc_head { get; set; }
        public decimal? f_cbv { get; set; }
        public decimal? f_cbp { get; set; }
        public string ind_scale { get; set; }
        public decimal? scale_value { get; set; }
        public string scale_uom { get; set; }
        public string scale_curr { get; set; }
        public string cost_center { get; set; }
        public string profit_center { get; set; }
        public string gross_indicator { get; set; }
        public string analysis_code { get; set; }
        public decimal? rate_uom { get; set; }
        public string pay_term { get; set; }
        public string lic_type { get; set; }
        public string lic_no { get; set; }
    }

}
